authentik:
  secret_key: file:///secret-key/SECRET_KEY

  error_reporting:
    enabled: false

  postgresql:
    host: authentik-db-rw
    name: app
    user: file:///postgres-creds/username
    password: file:///postgres-creds/password

server:
  ingress:
    # We manage this separately
    enabled: false

  volumes:
    - name: authentik-db-creds
      secret:
        secretName: authentik-db-app
    - name: authentik-secret-key
      secret:
        secretName: authentik-secret-key

  volumeMounts:
    - name: authentik-db-creds
      mountPath: /postgres-creds
      readOnly: true
    - name: authentik-secret-key
      mountPath: /secret-key
      readOnly: true

worker:
  volumes:
    - name: authentik-db-creds
      secret:
        secretName: authentik-db-app
    - name: authentik-secret-key
      secret:
        secretName: authentik-secret-key

  volumeMounts:
    - name: authentik-db-creds
      mountPath: /postgres-creds
      readOnly: true
    - name: authentik-secret-key
      mountPath: /secret-key
      readOnly: true

redis:
  enabled: true
