apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-secrets
spec:
  secretStoreRef:
    name: site
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: 1h

  data:
    - secretKey: uuid
      remoteRef:
        key: wave-5/forgejo-runner/config
        property: uuid
    - secretKey: token
      remoteRef:
        key: wave-5/forgejo-runner/config
        property: token
    - secretKey: registrationToken
      remoteRef:
        key: wave-5/forgejo-runner/config
        property: registrationToken
