apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik-private

resources:
  - ingress.yaml
  - network-policy-core.yaml
  - network-policy-egress-argocd.yaml
  - network-policy-egress-forgejo.yaml
  - network-policy-egress-frigate.yaml
  - network-policy-egress-grafana.yaml
  - network-policy-egress-headlamp.yaml
  - network-policy-egress-home-assistant.yaml
  - network-policy-egress-hubble.yaml
  - network-policy-egress-longhorn.yaml
  - network-policy-egress-mosquitto.yaml
  - network-policy-egress-obsidian-livesync.yaml
  - network-policy-egress-photoprism.yaml
  - network-policy-egress-traefik-private-dashboard.yaml
  - network-policy-egress-traefik-public-dashboard.yaml
  - network-policy-egress-vault.yaml
  - network-policy-egress-victoria-logs.yaml
  - network-policy-egress-victoria-metrics.yaml
  - network-policy-egress-whoami.yaml
