apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cnpg-system

resources:
  - https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.11.0/manifest.yaml

patches:
  - target:
      kind: Deployment
      name: barman-cloud
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: barman-cloud
      spec:
        template:
          spec:
            containers:
              - name: barman-cloud
                resources:
                  requests:
                    cpu: 10m
                    memory: 32Mi
