---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-s3-credentials-secret
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBYdXpjtz+Fzp3svXRZ6yqkWQ/46I+i2pcCtoaYiNib0eAvwSNBdkR7cZOApHZbsL3HxN2ZrgCKNQilwqvzo8w5ga9GpFU76fmKwPPP3FXsS4VSbk/KuU6OgIsF1DbML+3m7cTvcjARAhRMYrse0euuwlsmSzttlVPDJUdwPC4gATPVdR6LDmoADUKHpDPOuDTbhjKlV7VNfmn1E70fyEADZh8vBNUd3Q2pNvWsY6fYmlGuhqOQwfL7PGxJx1tbEvOcBtpZIfAIBTtfKy67+HjRx/4RkYabQtWqDmYJ4YVW0/TclZayuTSvReet5B8OTZZ37H/v0w1bMcMBevqWzaXP9xGPIwqM2O40AhUJLCcorqP4ye2abGLGYCXJ4mj3ld2YLKiKz3HSdJgVxHpU0ar5N51sAXni8wEhTJe90EKvelU+BOJ9/Vq2ONiat4Ttm5WDPbejmH/8R5ZCar6v+LCRn+VCqkuRup29VAUCWTtE31JkBFCNalUgsE6voMJHLpUgTWO2nOaWG1CX+OUjBHX8SwSvBCeM8Xa53XBqKPdBVzlGFUxREkWv6mMa3lgT7GVa2nZp1NEx/hQMTo0hRByR4WALXozr40XXDsK6lKQ9o+kp/PxH1t75zpZZRnhQUnHGRgZGOeuVswHBZeGzQF5uXyBUYBDwwdkNDFKgHJjf3+OGnjKBRZ1CHhHcaVi5tAf3TwXyK5yA/a4eknXWXs7Oaan5gg==
    AWS_SECRET_ACCESS_KEY: AgAT4A9wF4udKJT6XYtahw1CSE4Qnr/5fSdjgrt9hdtKkigiVyhNvkvfY/LKBvKSmuos/eB96cyZ9z3kqaayUl3628bBLCuz2qp0kvWUuTDNxRJyD4FiagH0GwpcjeJcTqAeD3viX8U9xjnJuvCHwRP8FODN8bHUn0fl/ncgnY+ZPdVUOlj+UwuxmaKSmcQCqOC28ov3dQxwrP6geoCJ7/L9cgoaGKSrSmTeHovmN4Afq7n8331bFDZPEizdB+dmZIZz7NeRTSkE2R8VCYeCByroFifEsS1+1mGCwwMJhAsm6mP/QuDOjazBX7gWG9LlCceTl9/Xmw4y+aK9Uibt7XzvgKxr/GsQVhLEAJpCynHjGugTCAGH+LjNqKBW4+pEsZupUynBObZow0SYlgkECiZhZQkoiWQH3t+nhElgrm8QD31I2Tt3I+Vt6Vag+FLCqbglaEUXN/XKPbQ+K0wcQ0/1wQySB3qfd9l1OFrtxmnsMUzS/M4v0WaQgu8MbW9mMeURd/XoMMIymnb85NBc0XzDYu4+qpHAywauKs0L9v1B0IWSYEgU4B6CT1enp3dn0G+f7O481NPpsHoZtW4DNULvzZwjDgHb0rffQ1gdYTRbrkQIh6W4yttvgA/qiO5V3BXwYb7Kfse7COsGfbjcTzN52mEPezFHXmaGCjOKnhKVgfx3ZfoQ+AClT2Z5N+fv05wyCxkoT+RdB1SIHqIP3NsTB9QQL7C73APxEhaxD6SgTYSREZe/a8cV
  template:
    metadata:
      creationTimestamp: null
      name: aws-s3-credentials-secret
      namespace: longhorn-system
