apiVersion: apps/v1
kind: Deployment
metadata:
  name: tandoor
  labels:
    app.kubernetes.io/name: tandoor
    app.kubernetes.io/instance: tandoor
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: tandoor
      app.kubernetes.io/instance: tandoor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tandoor
        app.kubernetes.io/instance: tandoor
    spec:
      restartPolicy: Always
      serviceAccountName: tandoor-sa
      containers:
        - name: recipes
          image: ghcr.io/tandoorrecipes/recipes:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /accounts/login/
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /accounts/login/
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
          volumeMounts:
            - mountPath: /opt/recipes/mediafiles
              name: media
              subPath: files
          env:
            - name: DEBUG
              value: "0"
            - name: ALLOWED_HOSTS
              value: '*'
            - name: CSRF_TRUSTED_ORIGINS
              value: "https://tandoor.indigo.dalmura.cloud"
            - name: TZ
              value: "Australia/Melbourne"
            - name: TANDOOR_PORT
              value: "80"
            - name: GUNICORN_WORKERS
              value: "4"
            - name: GUNICORN_THREADS
              value: "2"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tandoor-secrets
                  key: SECRET_KEY
            - name: SOCIAL_PROVIDERS
              value: "allauth.socialaccount.providers.openid_connect"
            - name: SOCIALACCOUNT_PROVIDERS
              valueFrom:
                secretKeyRef:
                  name: tandoor-secrets
                  key: SOCIALACCOUNT_PROVIDERS
            - name: SOCIAL_DEFAULT_ACCESS
              value: "1"
            - name: SOCIAL_DEFAULT_GROUP
              value: "user"
            - name: SOCIAL_AUTO_SIGNUP
              value: "1"
            - name: SOCIALACCOUNT_LOGIN_ON_GET
              value: "1"
            - name: HIDE_LOGIN_FORM
              value: "1"
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: POSTGRES_HOST
              value: tandoor-db-rw
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tandoor-db-app
                  key: username
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: tandoor-db-app
                  key: dbname
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tandoor-db-app
                  key: password
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: recipes-media
