apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor-credentials
spec:
  secretStoreRef:
    name: site
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: 1h

  target:
    name: tandoor-secrets

  data:
  - secretKey: SECRET_KEY
    remoteRef:
      key: wave-5/tandoor/config
      property: secret_key
