apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor-credentials
spec:
  secretStoreRef:
    name: site
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: 1h

  target:
    name: tandoor-secrets
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .secret_key }}"
        SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
              "APPS": [
                {
                  "provider_id": "authentik",
                  "name": "Dalmura SSO",
                  "client_id": "{{ .oidc_client_id }}",
                  "secret": "{{ .oidc_client_secret }}",
                  "settings": {
                    "server_url": "https://auth.indigo.dalmura.cloud/application/o/tandoor/.well-known/openid-configuration"
                  }
                }
              ]
            }
          }

  data:
  - secretKey: secret_key
    remoteRef:
      key: wave-5/tandoor/config
      property: secret_key
  - secretKey: oidc_client_id
    remoteRef:
      key: wave-5/tandoor/config
      property: oidc_client_id
  - secretKey: oidc_client_secret
    remoteRef:
      key: wave-5/tandoor/config
      property: oidc_client_secret
