apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: tandoor-postgres
spec:
  configuration:
    destinationPath: "s3://dal-site-backups/indigo/tandoor/postgres/"
    s3Credentials:
      accessKeyId:
        name: tandoor-db-backup
        key: access_key
      secretAccessKey:
        name: tandoor-db-backup
        key: secret_key
    data:
      compression: gzip
    wal:
      compression: gzip
    tags:
      site: indigo
      service: tandoor
      db: tandoor-db
  retentionPolicy: "3d"
