apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-media
  labels:
    app.kubernetes.io/name: tandoor
    app.kubernetes.io/instance: tandoor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cluster-regular
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-static
  labels:
    app.kubernetes.io/name: tandoor
    app.kubernetes.io/instance: tandoor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cluster-nobackup
  resources:
    requests:
      storage: 1Gi
