apiVersion: v1
kind: Service
metadata:
  name: tandoor
  labels:
    app.kubernetes.io/name: tandoor
    app.kubernetes.io/instance: tandoor
spec:
  selector:
    app.kubernetes.io/name: tandoor
    app.kubernetes.io/instance: tandoor
  ports:
  - port: 80
    targetPort: 8080
    name: http
    protocol: TCP
