---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: todo-secret
  namespace: todo
spec:
  encryptedData:
    SECRET_KEY: AgB5Q2MBvCeafHB1YUSV68YEobTMmIr/3Rmn0lI0E8ybnsf37F7p84dUi0fd5AI/LXkuEz1tDhbCf0q8eOxZSIgDdmju+wtqHEDnIAVfAc8dAB7gcMjf4+4xNAYyeVlFQbLH7zyA8b6w7NLRxk6Cs5gh4VFJ67gzOeflPo9HfoY8nGBzz3otLcjicClP+XQWVi8HU9xSXxABf6io3MFxrXCLqX0WAd9NY9e+hwmrxszjFAoSpKO053QDwK9zAbNcPB9/3cZPovUD7ImuB/dczI8ZZOKBgVZQ4rSbIDDBcrjW2eXnujsQENXngWgCjP0yFWXcHKruvcjUW0YtDLwtqJP3/vNNapjqQ4i72rY9qiJJvzjl3/AhBC7l5ClImU99wEAkVF4WDOlINlC+ot8tD5Or9ELu4/+zYmI5GPz3BLmbRrcZUSU5Id2OBJLOAcXVt4hA8TximQ+/YlXssrVK8ALaTlKYccHqym4lh9aWlsfSoqWz37Xot62rFPCv7g1XntKgpcST+GGbGiGrRv7e2wQKMctoWO0lKxsdknjQpXsmRN0kiLGPxEvY8Wh04izaQGbQbIe3Yrny6e7V3723aq7eokTLaceXYuHqWv0vZ2a9vnCCUO7JImT+kz5VsT/EI9LwSolfGIev+wy+zii9k1IEkE7eReN14nIFOceG5zzO/9yKJUISiLlzQZRqOPtjjoSl7dJmg0qtMl49SI1Kv3JqcR8YnAAq+m+Rn/DQOVdIBORloYo+/1T8W5+APZpcrkVcMQQ7M6xhKvQRQ5LfRV8G
  template:
    metadata:
      creationTimestamp: null
      name: todo-secret
      namespace: todo
    type: Opaque
