---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-db-backup-secret
  namespace: todo
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCA+UX8BKwrAgRZG38jnpYEr5VKcXGfgbp/XqdzaJ4JDxhY0hXxd+01Tt8Qa2bdnEoyProM8cjUmJWaPQIojTWcXels4qnjORL5efGDEcj29hxe6SEswRUxkoeNacbXjg2OXgnmNbUsGNMAhjOMI8dkho0Yxau9R0LB6wrPAsqLqqnmVMJ7VuOz2Ix0dknFtAAjLEidi5pjNuvVYbcqORcwNCcY0S7YOcAN4OxXmKqv0OELa9jWXVnl3m6WIbKLI2gteTBeZTAOPZyEzET+RFruOTbFirYpyAEZfM9wKrb2vVOzEZVfpLY6NwMuaByqaWa1vBNFH1ECzL+SLSh7VfGwvhPoLteWF7f0NABtJirFi3kt1zR8e6CWRQOEKOwWQGE229cQz0N8Y7KLRsdAFTes1yujTu16g1KnEWc5dQ5JVR76CVHJLhsmUDZE9Yi2iNhdSWke09HZBnoSWmpzeplwSgdWBrD6dkWDTLO1LQXCl3FqFKyRMdSMebAdxWsAX3bquZuAQmiROEIxML2E7jlUha12XAm3KTNlfEjajPuHOBYdsOY7bZ3qDt0GB4fTu/ZwCXpJfz0ywd4WM1aF59p01sNpQQfPQvo56OlySpA8SaHK7Yn1FcUVmYW9AH03w58OHpDqOeGRL5dg7fi1AGBwOrD0fu9MGi8nx4AOjm/U5hLx6OEeysu5XuX7FdL7qoT7938kShMGsBo17kFc0Q6RWJAxlQ==
    SECRET_ACCESS_KEY: AgCfH6UGaRU6JU3hNW10QLz6HJL+WCGXuIYiENiC86K7we+6dLUEWRk+ppcEYGEf5JjbOGh6u2ar2O/R+cJ7H30osPRjjt4RiBayjWcpjKUxoF/ZVHBfAvasC96GGSv7963/wb39elOEwQNNkLYmFFe9NwXGIij0qT6+5cmbnq1FMMGrM6TJ0FZB5FMHFuZoA98Vm17qPwiwyjMCRxIIlms9bw21VjoZPac1kO/KoVwwe44TlDOtAQxRvmY/NZYfb6LLFb+w64epSUhXd6gVleSHkX8ZqYqV7RoKdXSWZbZTqSOXYzUz/gYFGVDw9BoNUmKtigzVahqcyyufIgu4cUSkNJQuoHr8wZiKdmFQo8w8xz+8qG9ri42cmGf72VxHd6pBqdVUhx88Oks/mNY+0+RGdO8+NVX0dmE0ADaJbXJ7E6uE3qSPsLSdH7wn3/cLeE7BbKhX7FYX/ewMhSi+0HxSOIKWVtBcY6osngsmuOWK4TONBtrZyt/zcMMnolkFrPT09em3FNmhdu+lk3Sog0RBb9zfiIhSPshC5Muap9xo1XGbccBcCJUiAeTl/RahaadynUpZ/606uzs3/io7p3WYo0Tr9TG+tJjTFPSBUwRY3x7fxrtVa/fxxXFsOntL+iI58tgHIuSwbqQgX7UF79AXsnqWopFtxr4vxvZq0Lt/WbtSxQODE/FhB9WLnYgTOTlstJofqY+1dqARvZJ/lpqrR9E9GMk7WaLCrQLOPoJB2PEDNeZ0GDos
  template:
    metadata:
      name: todo-db-backup-secret
      namespace: todo
