---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db-backup-secret
  namespace: n8n
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBslsTLMKVCGOwsTVi5URJhKgqQp9dHVKjmbZIAsqdEJF0BDnzuHqpOaLMtEbz9YlIixAu6zR+c8RthzgE6QMtbJMT9ortHFJon+TWKnnd7bu0qevfNS3pYUhlH5mdqVW/LnHsuOXSL4HuKQsqLIrVG+OUQmIRBnBx3RjGekjZZxDYuG4mi0c59G5tBXpjup9DEK9ie/ftnJJYSdqszyvo1FTNXWU9tP52v7QaEiftkyd5BvFtUedRho7fp4fq9lq5eqLQ+pUBPZrnr6wsHDwKYXrbO9Y01tkH+ADjSRzZfobcI9FuuFZ3I5gn49M4aF/YyegHdpVQlqLXPWH91cuCGe3YLqtJA5RuQc8iprA1kGQ9xbZlxANmhvIJ59d5ry0IAG0WWqSJMm3xOTyxDG0E0P+pORlZt8MX77yRxsAAU3D5RwQkQ68/5h8y80iFirLVWN10Sx5FAbdITXkEUuM42kQHK5Fa0jiuqZuFlVDFujXggISRLj8d0S1RS8vUisG81qhhD3mw/YiGwQkrx/9hgjFTZ1F5u0KIHqF+iCDe3bUhXY5rEJTMk2PAkh+vcjVuMYDldTLxSDFawY+5Xi0pVc7kKzNrJk4gpglfKNK6rMzs9l5SBAeHkSbjRxbH7ZPGFqm9tO2jUmN27Asi1F9g1xRm+UC9iiI9AUdWxrZqjrPpl257Ovr/nWg5zlAH/Jmzg+1hcFCI7o0d0Vjd17T0FuTHL8w==
    SECRET_ACCESS_KEY: AgDEflvc43/56WYGL/fgdxIXDDemZMKECU+4YPEwYH19VTcwyStFKodAFxFmdxxicQtzWTH6KXXwu9/OxkmlQUnT30K15KluCB01M3ZmM7F+8dxXQvsQO3ZpyUDFYlBvqq5+jvcB29Zc/Duc2NS6Ff+JlN2f96r/3sRc9pWxXGlkxup3PXvs5xhKBas+OriMidzUkyW+TnO/1yVRbH6RFkkw7inPJtwp89u5ryl8Xv0ftKprfy3Cf1uC7m/zqjOHh5pC55j2RT2bTc+VBOKNEShFAyY2sxJTDtb+FUryXddD2+GevFXcb+cNli++QtBiPF5ZXXl13Tnu3mRJZ4X8aC4MYpHV+beal8GFKm/wTuYA1vnFKQuT4Xgj9SS3L1aBJtbvs9bgADB26C5h7IgXMRJ4dJYfHAWR9HYY8dOIOrsuM2XKfdTfSwgJab6yf9NUgCLi3DCAqkikNuPEHZTunY+mZkjZ5xCWeEO2yiEiLfEBc2F1ul01LLDIdsbpX/+9aSMxBhaYgDxkS3NkAzKDAwO4NatFqQzKWENIplbGeKLeA/g6nJN9Hsml3GbNT5+FsUzFSETZyzEcTMW0IxbdBN7F2r7a5uBG4mGCXriOaL+w6YOkEHFxQFDSIQ0oxMvaBu2liPucKqQFPxQEuZP2eN3Pf13T1mfPPBV/02hTNdJsNquHLGIys8G2wa6aa5TAsvDVfvKEIQK4Vihe3QPU+lh+CVF1OkrqWGujUaYSmyBX2WEfz7hafvky
  template:
    metadata:
      name: n8n-db-backup-secret
      namespace: n8n
