---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    encryption-key: AgBEG4Cl8T20LrAXWNW5sa9K7BWF6VXrMfsnE6FSuWixed3BgHCEbmHqTjuB7AZy8uSdVT99jESr7fstTj2cnhZG18e/BYaJTldzWSixGgXS7LG1MayGvpxdbf/18FM9Q61HoMefwf4tIqRYTCJIPUYLLIH7zrfiiia0dto6OJJUbQlMS8ocO7u4yI2yKpXUBZge5zE0Xwo1jPt1UtRnmtoGzBngTS0QDQEYY6rt1WVOmrDdumgWZD9q1AOQNA5eRCgNVmgTwS7DZo0BtEMxKVc+sts/wJHzez+/I5jDX9Q75mAVzRmdymwGAsCaj1HjpbmEnUM4ISPJaj/B7H4hIZYXmyYUBGMzmkLH4q2GJW/4z8MIGKz5UhbcWZD3tt/oFyLlEtsdfzXbHkva6AUyKXiV4VjhbR3ca2yBDKEKlbY90a9OyhLW9jGIJ6ZO0cnnCQPRQ0U/tRrG7uOZJ4xOMagUV7+ENIhI2nLERCA6wIBt8VuRmyehOZoyuY3dr3iGFcPpuvAu3WFHyzhjZ0lzkbr6Hwzna9HVu4PeqN+3D99awwnhTUagXac4K5YnQOxXZs4YIzWQXbbHxRlDlKAR/miEP38GEyyI5vL0iXpsA6a3sZ/Bn+tpLDfSD+HSpX3iW5vX9UhKwEGO3LuFwANnCZZGblEslGfGa9lS54OV1O5XwOCcH07PPxLJX6jjRg6pGblk+HkRjr8og0tnyvu9QV30LDdL6DK8OxyAOk0xWQx32A==
  template:
    metadata:
      name: n8n-secret
      namespace: n8n
