---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
spec:
  description: "n8n Workflow Automation DB"
  instances: 1

  enableSuperuserAccess: true

  primaryUpdateStrategy: unsupervised

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 17

  storage:
    storageClass: cluster-nobackup
    size: 5Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: n8n-postgres

  postgresql:
    parameters:
      archive_timeout: "30min"
      max_connections: "100"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: n8n-db-backup
spec:
  cluster:
    name: n8n-db
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
