kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
spec:
  template:
    spec:
      containers:
        - name: traefik
          args:
            - --api.insecure=true
            - --api.dashboard=true
            - --providers.kubernetesingress
            - --providers.kubernetesingress.ingressClass=ingress-public
