apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dalmura/workloads.git
    path: ingress
    targetRevision: HEAD
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
