machine:
  nodeLabels:
    topology.kubernetes.io/region: "melbourne"
    topology.kubernetes.io/zone: "indigo"

---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: "talos-<HW_ADDRESS>"
auto:
  $patch: delete
