apiVersion: v1
kind: Service
metadata:
  name: sidero-controller-manager
  namespace: sidero-system
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.77.140
spec:
  selector:
    app: sidero
    control-plane: sidero-controller-manager
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: tftp
      protocol: UDP
      port: 69
      targetPort: 69
    - name: siderolink
      protocol: UDP
      port: 51821
      targetPort: 51821
  type: LoadBalancer
