---
kind: Deployment
apiVersion: apps/v1

metadata:
  name: fio

spec:
  selector:
    matchLabels:
      name: fio

  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null

  template:
    metadata:
      labels:
        name: fio
    spec:
      containers:
      - name: perfrunner
        image: alpine:latest
        command: ["/bin/sh"]
        args: ["-c", "while true ;do sleep 50; done"]
        volumeMounts:
        - mountPath: /datadir
          name: fio-vol
      volumes:
      - name: fio-vol
        persistentVolumeClaim:
          claimName: example-jiva-csi-pvc
