apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-secrets
spec:
  secretStoreRef:
    name: site
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: 1h

  target:
    name: matrix-secrets
    template:
      engineVersion: v2
      data:
        macaroon_secret_key: "{{ .macaroon_secret_key }}"
        registration_shared_secret: "{{ .registration_shared_secret }}"
        form_secret: "{{ .form_secret }}"
        oidc.yaml: |
          oidc_providers:
            - idp_id: authentik
              idp_name: "Authentik"
              issuer: "https://auth.indigo.dalmura.cloud/application/o/matrix/"
              client_id: "{{ .oidc_client_id }}"
              client_secret: "{{ .oidc_client_secret }}"
              scopes:
                - "openid"
                - "profile"
                - "email"
              user_mapping_provider:
                config:
                  localpart_template: "{{ "{{ user.preferred_username }}" }}"
                  display_name_template: "{{ "{{ user.name }}" }}"
                  email_template: "{{ "{{ user.email }}" }}"

  data:
    - secretKey: registration_shared_secret
      remoteRef:
        key: wave-5/matrix/config
        property: registration_shared_secret
    - secretKey: macaroon_secret_key
      remoteRef:
        key: wave-5/matrix/config
        property: macaroon_secret_key
    - secretKey: form_secret
      remoteRef:
        key: wave-5/matrix/config
        property: form_secret
    - secretKey: oidc_client_id
      remoteRef:
        key: wave-5/matrix/config
        property: oidc_client_id
    - secretKey: oidc_client_secret
      remoteRef:
        key: wave-5/matrix/config
        property: oidc_client_secret
