apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-media
  labels:
    app.kubernetes.io/name: matrix
    app.kubernetes.io/instance: matrix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cluster-nobackup
  resources:
    requests:
      storage: 20Gi
