apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-secrets
spec:
  secretStoreRef:
    name: site
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: 1h

  data:
  - secretKey: PLEX_CLAIM
    remoteRef:
      key: wave-5/plex/env
      property: PLEX_CLAIM
