apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: plex-secrets-config
spec:
  type: kv-v2

  mount: site
  path: wave-5/plex/env

  destination:
    name: plex-env
    create: true

  # static secret refresh interval
  refreshAfter: 5m

  vaultAuthRef: plex-secrets
