---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: plex-secrets
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: workload-reader-plex-secrets
    serviceAccount: plex-plex-media-server
    audiences:
      - vault
