apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: code.forgejo.org/forgejo-helm
      chart: forgejo
      targetRevision: 15.0.4
      helm:
        valueFiles:
        - $values/sites/indigo/clusters/dal-indigo-core-1/wave-5/values/forgejo/values.yaml
    - repoURL: https://github.com/dalmura/infrastructure.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/dalmura/infrastructure.git
      path: sites/indigo/clusters/dal-indigo-core-1/wave-5/overlays/forgejo
      targetRevision: HEAD
  destination:
    namespace: forgejo
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: forgejo-admin
      jsonPointers:
        - "/data/password"
  revisionHistoryLimit: 1
