apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://blakeblackshear.github.io/blakeshome-charts/
      chart: frigate
      targetRevision: 7.8.0
      helm:
        valueFiles:
        - $values/sites/indigo/clusters/dal-indigo-core-1/wave-5/values/frigate/values.yaml
    - repoURL: https://github.com/dalmura/infrastructure.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/dalmura/infrastructure.git
      path: sites/indigo/clusters/dal-indigo-core-1/wave-5/overlays/frigate
      targetRevision: HEAD
  destination:
    namespace: frigate
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/audit-version: latest
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/warn-version: latest
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 2
