apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: pajikos.github.io/home-assistant-helm-chart
      chart: home-assistant
      targetRevision: 0.3.45
      helm:
        valueFiles:
        - $values/sites/indigo/clusters/dal-indigo-core-1/wave-5/values/home-assistant/values.yaml
    - repoURL: https://github.com/dalmura/infrastructure.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/dalmura/infrastructure.git
      path: sites/indigo/clusters/dal-indigo-core-1/wave-5/overlays/home-assistant
      targetRevision: HEAD
  destination:
    namespace: home-assistant
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 1
