apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
      chart: plex-media-server
      targetRevision: 0.10.0
      helm:
        valueFiles:
        - $values/sites/indigo/clusters/dal-indigo-core-1/wave-5/values/plex/values.yaml
    - repoURL: https://github.com/dalmura/infrastructure.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/dalmura/infrastructure.git
      path: sites/indigo/clusters/dal-indigo-core-1/wave-5/overlays/plex
      targetRevision: HEAD
  destination:
    namespace: plex
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 2
