---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-db
spec:
  description: "Forgejo DB"
  instances: 1

  enableSuperuserAccess: true

  primaryUpdateStrategy: unsupervised

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 17

  storage:
    storageClass: cluster-nobackup
    size: 50Gi

  backup:
    barmanObjectStore:
      destinationPath: s3://dal-site-backups/navy/forgejo/postgres/
      s3Credentials:
        accessKeyId:
          name: forgejo-db-backup
          key: access_key
        secretAccessKey:
          name: forgejo-db-backup
          key: secret_key
      data:
        compression: gzip
      wal:
        compression: gzip
      tags:
        site: navy
        service: forgejo
        db: forgejo-db
    retentionPolicy: "10d"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: forgejo-db-backup
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: forgejo-db
