apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik-public
spec:
  encryptedData:
    key: ""
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: crowdsec
spec:
  encryptedData:
    key: ""
