apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cluster-site-crowdsec
spec:
  conditions:
    - namespaces:
        - "crowdsec"
        - "traefik-public"
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "site"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "workload-reader-crowdsec"

          serviceAccountRef:
            name: "crowdsec"
            namespace: "crowdsec"
