apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: crowdsec-bouncer
spec:
  externalSecretName: crowdsec-bouncer
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - crowdsec
          - traefik-public
  externalSecretSpec:
    secretStoreRef:
      name: site
      kind: ClusterSecretStore
    refreshInterval: 1h
    target:
      name: crowdsec-bouncer
    data:
      - secretKey: key
        remoteRef:
          key: wave-6/crowdsec/bouncer
          property: key
