apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-secrets
spec:
  secretStoreRef:
    name: site
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: 1h

  data:
    - secretKey: csLapiSecret
      remoteRef:
        key: wave-6/crowdsec/secrets
        property: csLapiSecret
    - secretKey: registrationToken
      remoteRef:
        key: wave-6/crowdsec/secrets
        property: registrationToken

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-enrollment
spec:
  secretStoreRef:
    name: site
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: 1h

  data:
    - secretKey: ENROLL_KEY
      remoteRef:
        key: wave-6/crowdsec/secrets
        property: enrollmentKey
    - secretKey: ENROLL_INSTANCE_NAME
      remoteRef:
        key: wave-6/crowdsec/secrets
        property: enrollmentInstanceName
    - secretKey: ENROLL_TAGS
      remoteRef:
        key: wave-6/crowdsec/secrets
        property: enrollmentTags
