apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - secret-store-site.yaml
  - cluster-external-secret.yaml
  - middleware-crowdsec.yaml

patches:
  - path: patch-probes.yaml
