apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
  namespace: traefik-public
spec:
  plugin:
    bouncer:
      enabled: true
      updateIntervalSeconds: 60
      defaultDecision: allow
      crowdsecMode: stream
      crowdsecLapiScheme: http
      crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
      # Reference the file mounted by Traefik
      crowdsecLapiKeyFile: "/etc/crowdsec/key"
      # AppSec configuration
      crowdsecAppsecEnabled: true
      crowdsecAppsecHost: crowdsec-appsec-service.crowdsec.svc.cluster.local:7422
      crowdsecAppsecFailureBlock: true
      crowdsecAppsecUnreachableBlock: true
