apiVersion: apps/v1
kind: Deployment
metadata:
  name: crowdsec-lapi
  namespace: crowdsec
spec:
  template:
    spec:
      containers:
        - name: crowdsec-lapi
          livenessProbe:
            periodSeconds: 60
          readinessProbe:
            periodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crowdsec-appsec
  namespace: crowdsec
spec:
  template:
    spec:
      containers:
        - name: crowdsec-appsec
          livenessProbe:
            periodSeconds: 60
          readinessProbe:
            periodSeconds: 30
