---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: iam-credentials
  namespace: external-dns
spec:
  encryptedData:
    credentials: AgA669LHL1ORjxHe8jmLRK8UwhZDA6ZEfIrfdUWiHGj9KvTLmZWDWISoSPRRsOGsjvB0gllrNj2ELLck6lpqEUjGozqyPcInJJYJsLwiIhesl7BEAyrx9Pdpv1ncWQhAZsbm4M+QjK3Z/3y6OkFfE/FA3VrPXxUZY+HPboatJLmosx0P+2FqBVSSG2oOL6kDE0HnK7LWp/5WjGeCAnlk2FzyE0ddakcZvLQ3ulZjlzIjE1l+px3p1e9amFrHWrUXSpx0pH0OUiElWrB+gutWtL7fMsR/S9OERWO6xPnJ4wlEucIUdybzRjjY/WSRYZDOcF1yHYH0+Swdk9deHHlrm6wN6DSJrDG+L9dMp0SIhSu3xk9cozd/hCvLUoZRIS/HVxRvgwKWem3ddclj6JIi2GDqeLyuVBYHOJnmph+f2nVpRo+D7uk0w/lF+ymHRSGr+639Iraf5VL0dazWqq1xgDgqXkLv9qMPN8niMwjQyIckSCL/Kvg5XZxmpmJP68RwNuVrnLZfU7wPO6ISDw1+tQ+6+X4EbpQcKEwvdl8WqIMMUTLnsFhyhSbR501PW/32qZ/qAvsAzp1eMAK8CYoQV+x788UWHa+xpWCLbh/s+V0CdlQE/n+PFnejQUqRXN0SWNCZKNfiWa9SDKBiUz2GZ2zk58R9dKgSCK4XU0ASXtIHzSUtDU7ckclosbjMnmvnjzCQ3XTymYM3H3aTxu5my+QWk1ovpERdNPQBe+772x8H7MyVMy7kLPhoMsfVOwYlaG562B0wMOLt+wk7te9jd5W2KYzj35U9IKREZGQ4SSD1E/xqfh81f3Qsb8vaXsAefYOafIM0ALVcJT/wXT9hj0w2oJV7ug==
  template:
    metadata:
      creationTimestamp: null
      name: iam-credentials
      namespace: external-dns
