global:
  checkNewVersion: false
  sendAnonymousUsage: false

deployment:
  replicas: 2
  revisionHistoryLimit: 0
  lifecycle:
    preStop:
      sleep:
        seconds: 15

resources:
  requests:
    cpu: 25m
    memory: 96Mi

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: '{{ template "traefik.name" . }}'
              app.kubernetes.io/instance: '{{ .Release.Name }}-{{ include "traefik.namespace" . }}'
          topologyKey: kubernetes.io/hostname

ingressClass:
  name: ingress-private

providers:
  kubernetesCRD:
    ingressClass: ingress-private
    allowCrossNamespace: true
    defaultTLSResourcesNamespace: traefik-private
  kubernetesIngress:
    ingressClass: ingress-private
    publishedService:
      enabled: true

ports:
  web:
    port: 80
    http:
      aliasHeadersStrategy: delete
      sanitizePath: true
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    asDefault: true
    port: 443
    http:
      aliasHeadersStrategy: delete
      sanitizePath: true
  traefik:
    port: 8080
    expose:
      default: false
      dashboard: true
  ssh:
    port: 22
    expose:
      default: true

service:
  annotations:
    metallb.io/address-pool: servers-vlan
    metallb.io/loadBalancerIPs: 192.168.81.11
  spec:
    externalTrafficPolicy: Local
  additionalServices:
    dashboard:
      spec:
        type: ClusterIP

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--api.insecure=true"
  - "--metrics.prometheus=true"
