global:
  domain: argocd.indigo.dalmura.cloud
  networkPolicy:
    create: true
  logging:
    format: json
    level: warn

configs:
  rbac:
    policy.csv: |
      g, Admin, role:admin
      g, Viewer, role:readonly
