---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-s3-credentials-secret
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAdUOY6KFftHSV3nWfxeVGf9kW7Pk8XtMJOLMsXWQPOdDwZNHTDa9l0RncNmsTYu6i3GI019zBU8MCja9Ei+891IwAXoh2ztuOrSWYEvYzO5tMdQMNhWcuZ136msFDLwbfi6EmT/PvjxnZQZtCubdcsIJyCL8nWmUFfWGpWvWJ4suQDcccPwkMqs8F3FMyEEEXnWnXkgOOCUohoBOXEZxjJIRCvd+3UxOJObjdSn1QwTpTeTixyDp2zzYW+yhAdLrgi3W11nteYVnTb6CM/jBFzibkYtH8Pcw7yCCwYt3WweN2A0vsL2X9VS5rq3Dq1mBC+wxm7JyPgZ3Cfn45CuuPm1QGpy3fQRLv8D6AfEQjjvq1L4YtxfZiPqlT9l57Hn5G/JijMzAIqCrYjG/IeOTazTxJCjS0XN7LwMZ0S1aV+PS2D1kzAG2cMqkSkzzdhoMk5GhuwFsrRGcLQHoAR+5a8Fa6z0sGrDy+QBsDV8IdRKje+qGkEvtFdOvdnm6qOqrakL8kxAsdfQpCpYy8vsc5Zmnkn5Ci1u4bxajOoK4x8/iLX6WN9w56viJol0irzBx9blsWPP3CpgH42IV63e66RWjAybsfo7AfYpeNg2at5WYqbGG+jDFDqVWqzLuWH92ulKnLFjAnkZtczU11zqYb/v2grrysFhcHYtjU55wpwmfs6XMFwH/c0yTu/JbnZDXHvXRRLwGlbPHYPY1A0dSELry/M0A==
    AWS_SECRET_ACCESS_KEY: AgCUMGzmBW473eekUkP9nwPhbNrGOiS5XE7Vsegq2OsJoMLLQWev+lbLPcGvzKNMRXu21rzLI2jNzSGhRT7x/LB9dgdB/6+noRLgEJ1XCqtjG8KsLjL5l124d2A0KhU0ucmtQf7DJpIRoMzVJhZZOxDjCu3tC8YCalUHEOxGbj8nbu/AoNjr93iURoqFz8tz55fmu+SXo6WLYh5PBIvC4JX3vppDOQJ0Xc+XVtarAnqfnbamNv0HgkY0hxx/frsw0CiaK8Zcyk+/+OyPKR6qb92qEK7hnZ8wRPDVCP1HxfghC5gQmPKnAi4dm4cSazpC0ZA4tYWxLud/W/6qUwdZwyiqD/JU5e7/9W+WBcXv2Kuhc1noL7ZAtFm0kV7xyZEtr/hjrKJwuWBB8Irh7xvVeNrFMp4tDFJu5mWwDMhpK/nXEii1H13IUproU164KcnySFqCMR0kAMXrRe8AB9KrQnUx+wktoxBVJAfMTGYNlIsIY7qLfLV31L57n1sYx/oXQlHFPCcvqQ7qP32py6u4uWn9NEcVRYCY2R5KUCiiLHnLbRRcFbOGVN6kwCbEl9RriC+fjSyjMUchHqj2cuKIzJPRlT6FHrp8ufi6iM1prYl4rgfku0W82kUpPasiS/HdNKOdasjVDP567Idh0oXQvouKE8BAgkrIr0lgj+sE2ynKohKGIiMD0RD1HWWvNQwwJwg4dfkhlcqG1wutGU8ekdV/tfTfU5A+fpkaWYWJxCGcv1YTWpmwBv/6
  template:
    metadata:
      name: aws-s3-credentials-secret
      namespace: longhorn-system
