apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: grafana
      targetRevision: 11.1.2
      helm:
        valueFiles:
        - $values/sites/indigo/clusters/dal-indigo-core-1/wave-4/values/grafana/values.yaml
    - repoURL: https://github.com/dalmura/infrastructure.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/dalmura/infrastructure.git
      path: sites/indigo/clusters/dal-indigo-core-1/wave-4/overlays/grafana
      targetRevision: HEAD
  destination:
    namespace: grafana
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: grafana
      jsonPointers:
        - "/data/admin-password"
    - group: "apps"
      kind: Deployment
      name: grafana
      jsonPointers:
        - "/spec/template/metadata/annotations/checksum~1secret"
  revisionHistoryLimit: 1
