apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-single
  namespace: grafana
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.5.12
      helm:
        valueFiles:
        - $values/sites/indigo/clusters/dal-indigo-core-1/wave-4/values/grafana/values.yaml
    - repoURL: https://github.com/dalmura/infrastructure.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/dalmura/infrastructure.git
      path: sites/indigo/clusters/dal-indigo-core-1/wave-4/overlays/grafana
      targetRevision: HEAD
  destination:
    namespace: grafana
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 1
