apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts/
      chart: victoria-logs-collector
      targetRevision: 0.2.7
      helm:
        valueFiles:
        - $values/sites/indigo/clusters/dal-indigo-core-1/wave-4/values/victoria-logs-collector/values.yaml
    - repoURL: https://github.com/dalmura/infrastructure.git
      targetRevision: HEAD
      ref: values
  destination:
    namespace: victoria-logs
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/audit-version: latest
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/warn-version: latest
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 1
