---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: iam-credentials
  namespace: external-dns
spec:
  encryptedData:
    credentials: AgC6v/9a8TaxM/g4ZGASEdBuVRTv72SlNm8CdVRBaLxD+lPghykbmMEzvkMXc25M1etWZbEEky5GKxPAsdl39/HxSgXEA6LmqT2TVXYT8pxWDW8C8PuP9CY0msGzl3+lcg33w7zKDSDdzzWb5UtIaL0hjwde1nVxD/tydZARrPZLkQQWtm7ubdseXl22NzYFNzu2dZamzHUaXxOSiLNfcPJfSqTSzou7UFHzBH1sq5YexhBm1GPXtm+pUaRo4LADMk3BO8UqdWIaNH8uSPaF9HXcC7nwtp7UqPQKDlLHF4itcS6M8U7xx4d9kYYxPBhLPvKvGUB7TosowUId+lfLYT3VJwxcYCdu9zrQMLojbjFrLYpqCH5oYCsvTIrAR1DctHId1GtSvqk5UYNt2tHI+kygoduYCFTDjhNdsGToZJSgp2l+Qe91X7h/k6aOjERBWKEz8oFv4KiJr0UGGM+LA2eT4Rp3qBLD7MfVSFF+J1mEvfoW95BjKIRBYUBpB1rALMG9iqh/WjuZdTmy1NV0iH56Za+sk4xvjlvzuz2UlvW7XVR26yscNc0wwaw8Z5EszkVzn8bg8ecA2YDElEBPI5CACSKZigOHnP6mhgwBVaGdhngTRxRXswx/93+ejaeSLG8BbLsOZ71Bml4N9+2OiJQfc1C+QzssSBhCYxwskgQYJxUoiCgz3Ow/S9GD/XmVZd9n8pyKdx/AIfyibWrgdSTEOCAANcx4vH9srrq4i7J9aBsNFDOpPojQmaDn10JugAenG4X4a/KVOFff+LmJiDcdnYT0OaEGzg1rXKs+1Sf5e/+GyTMFkmpGnmm954GIqeYTLHzUU/R17M1FJpaXF146qsic8Q==
  template:
    metadata:
      creationTimestamp: null
      name: iam-credentials
      namespace: external-dns
