---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: iam-credentials
  namespace: external-dns
spec:
  encryptedData:
    credentials: AgAOJVLxc5F9YVjxUjMWoBaG3/VYl+pXn0lbhpX8qUb5xwF1Vm0HnpVJrtd6D93xetfD9GFzlULgWP/E/Solg/8nRcBJV8NaChy8xFkhKVVjYN1W1rezlOfa9xwI36kUmv5V3m+ybyDNWFZXZ5zeUxi4lZ4vkXakFTEQ57TKAbiznFf6zovSBQGsPxU0ejjDoe2h4uYH+Ak+0iwC/euVGHLS+8k5EaG5zpurheAb4vDRpd64OpLEbgUMoUhi3NBu5F0gjDtfbHWflLwr7hKwBLyKqkzqcXLBSKByeTo0uVbXrAWreADdCsQbs6qZSNdZMvx74QqSQbgHGbBy6wa4BaXlurT/NJ1mngWsmMOKZUKaOVkMXrDxASWDjPQnEWrH65zR/MYS/Mv4Oy7+/olqhxok8mxn+fXkYlSWXyi3jXk3b68tcDi+TM9jr+tywhJnH28oqimINOxafUpuijdvzOQWNKPY4jGByCGqbYBuhQpyM834pkQ+/WShOtmloUa5tNfx89fQaS5DwLDD7IBBDVjQtVg08LIJV9iSGoq6AXF2vWdSLme63MMBHPRMIZZHNBWAtdJT79QKGE05xeuwVj/wQxWEWvD7ZLKA+V1R7y85Ih3QFjqnKuhZlxiOZwifwaFLnQMPIeAoJbQft3wvgEAZ1lftJCPIAryEBBNqTJuPw7iVnAVrrqwy8FmKX56fcCpkaVfL4BIBEmZT4xnZbb7iqZ39uAMaKhmE08qLLpSyUlRF06SvnGNikZ/z08A7L8B/NLSDoy91Z9bKAydYYzmIs8iOqbd5J4EZFM5kebF4J0/BP+vxDPVwVC0e1MjCuOVSElxcrXZBhxAcMZzjuiCw/CuEhw==
  template:
    metadata:
      name: iam-credentials
      namespace: external-dns
