apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: review-bot
    app.kubernetes.io/name: review-bot
  name: review-bot-data
  namespace: review-bot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cluster-regular
  resources:
    requests:
      storage: 1Gi
