---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-s3-credentials-secret
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBofYZFg9FT7HSLD4a09JCHeOpq4lwnztWynK/hC5gE4LUVKQj9fE5o3jwgux0c5eHcC22RPdTSiObe3o5n/FM1DDb2AFo6uyePO7xp3t1EK2rvpDOVuE+Iwg9lIKdS5xO27aH92W/ux2V2d7q2hFsHxzyVV2yMGIzb5vu+5ePOaHxSsl8DXIl4N48LHuGrXqGH3CybqTNSEAbLsqCYT5q3t/kzhOZXdjsHafs7SMSsbWyPzPDu6kxJZFoL3BtMKqvejoxuF7pmzUU2l2P41FB4LTAputqQK8uCKmDZcmrxJrb9zeMb6ZeeyZ6CFfRWtF2l5XZ77GIes6WMEsyRmEc/aD/ao2Ij24rGMX8awwB1jgGzljgzVvx3APB9kIsUYZ/R9X7cS4c+YI6hwlcs48X61rbdPbw3FLH3ddiHCL19fa+L5x4Y96V0/VUofZLZw040FyMIdINCS+/d8rq8wVG+KZrxlnYC1BZ1pf5M49o1c9YRCS48caoupdek7F6T6RPvuTXTGerAzkpLZ49teHlgX5JSP7p2kaWLrCK4cua189w8VnqY38dNE7magpvwaI1lHuMLQOxBYyw/JLNy+qQP5c3M9R0wx73Qt0bVuPYNLqSq0WeestnYLWIXWvxWOJgEVDfrL82ePDCWF9ZYf/Zl3CLcgwWINrc0rdpdx3cj2l6G9UU5dQ+7EwXWJOEkzoqSfAy6j96oL/93wGPmnZsJ8DnSeg==
    AWS_SECRET_ACCESS_KEY: AgDSmIg168KO587A2Y617Chn6fee3R/Oj4Ibeoqgjp7CtME5/n1PWvK7x/dBmt/iUET5KSDCNOZpIliWMmPuxjtLHzfjsG9KjX24n3Lc6NKQ053RjYWcR3n03zlajq6mt8y1JrTDio5AUYIOkigc3FgrC1nYyF1/5xTImxvJ+7UtwH0co0C6u/m3l4xgxB2K6XLtjQRfllquOdNK7il+Aw4Kwnx/o0OsSPT7tV+JFjMlxylD2VVNOSUHu7Ly6JRSutylV3BjjadRqHuanJWjnXwxsIZAyQKjYaelCP8gNVAicbvSorReeW5ZdSglC6kh76mtl4OnNkmRmqsVOG9TYgim4JIut0JLdMQIoNC0qZluNlSsCxHnzbz/rRw9Uv5L1HVrbQlq5MX/X7DEJZEOkCbmVpprkEHHfgYOqrxPQqVa9PFli5oveHY0dvlBkI6qAUjavfuz1af8yHVMLsrZOpg5MHKGAheKb++uCtyaK/9x0qjlgT7EJuRX+st2yLl0Np7mXi3/sTuD3oALjRBOXp64w7/qj7DE1Pu+Ooj9qqrCSi1eQyBER7NHl+NYSsxzQgPkY5tZ4Iha3o3LAWesLAQaBG2HMfn1EQbr3XYMJv4TDOZ9vmc4iU3vkrve8aiDlvYpmIqt6v8dYqWV4cR60D/6cwdWFuOTcBhgh0Euf7JjmO5E1wpoQ25+pvPvDSUD2Z96l1bd/8WW6k2j4eUPl030Z8yQz4dFx/0FSlHRkMukcRIoVPU4IQ1p
  template:
    metadata:
      creationTimestamp: null
      name: aws-s3-credentials-secret
      namespace: longhorn-system
