---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-s3-credentials-secret
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCTBvHRc8NKVSBjKKoSdRvYaDGaKv4y73u2yXVs57HVPh+749bZnfXbptEQsxVgBiSpSTyG8YCc3ABqSbwH3WOcnyUiaF8/SuPTMR9tfTS4CTFrigOS7rauc81PdIqzsTnQOQXEi9mRpjDdAFvnyzvS1QWz2B2ug7zMQr8IKgPWT9qpWWFMiHsVdLRPztx7uZPz8yu4QS54y2gIpAGxRjhjHCQIzrQxXy831+OLHQpjwioitWpu3vcBDOo8OtwNGE4ltx/5vmdB5b6Fa9wR70sEChCfeLge7BXEQO3xzcSg7wUfuU02AZA9RTnRW59xqTgGuV8YRlwU85XKvTBGIxx4Z5ShqrwguRr03UOlUwMXWhh7CdO+ar5NT6Qa6dAgzfpwIPgjd9exaT50sUgUCSuKiBYpzu17lksXIY5MYvEDsOeb+UG39GlxvH5RhOAJ+w4BiP2W/Qioe5PP6YVTz5vk1SvBZI9MycNC43uGGXMJv+pcy/8teuk6s127T2N7tgfc3H2ISs6krMzBvAfsl5WGqS9fzXpxeSMWSFtpgGZz6OxfZQzar81mbCQPc8oMpqL1rUKbV3Jm+5Qm3qOZRIAMaPNd6T052kaqwdyy1K+TSaSNMcagPQxjl4V0WCN6p2Yn01hTvM0guGSEk/iisV9jsLYV2EfuhODw7/mOwwcFnGnPHUV/ffe/Hukv/C6kg5xmJ58lU9U0IK6oFeNLQGAAk4AusA==
    AWS_SECRET_ACCESS_KEY: AgAgVtLhjUj64r3AX6fs1XPk7pPCg9RJmqObK8cVO/ghvQ45vDIzLOj8B0BmT1kFTMzEuynW1N53x4pSv9kHg0TuBNpKDJSCU06c0EpkG00zv/9AVCETHpqvlD8T6TpLAYoBt4AzBnOQJLUe4rwC3MfIdhNg6CStj026H90pZpbFQ7WFmORcJ6AVrE5+C24vxO3/iUNSTPaMZPWwt3qKWrCZwpl7OkTSOI7bffwL4Ld5cWdWGE8IQUAOglTsjSCGfFwXbLhNWYZ3S09HnjbUSCPdypJ0z+X4sXQg7thrWiU7Gnfl0aUZevi2gvreiteUE3YHGSfZhOnQ17ACJIMXRJifM5vp+YHO9ndi6p/7ZMcPc7VbQYUbbNvKkVAzgtFjQviOF7HB4O8036ae8lU1i1qPIXYcCXHm5hspjsT4eK36oQGtcWU/hU333d2n0Tj1zZLeX+Gl5QLspiz1rmAE1sC8cK0ziHtROJuBZyrNsE91eWJz1UjWkhdXxNDsP9yVw3rw8rIDfPkQXJtXE5+OCn0RzZRX7CPR2XA7cw4KYMyolDSEkD150Wom+X7BsSDMB+PV82tWvo0qcSmm2iK+g59g7Fr1NhMSXFTqq3vqmWfyfWEo5wt/iYNSQNRKroEkcBFWNRz8IVkwDt3XWATDhVbkDm9KQmF5BoGkkmN9yabBZrPDqpsEqy72t+qwnJ7Nn1mIhO/ru9RFHIov7uh7e34MYGFKJ57fKWa5HhDYuwftqm/yPfd4IUwrVQ==
  template:
    metadata:
      creationTimestamp: null
      name: aws-s3-credentials-secret
      namespace: longhorn-system
