apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: frigate
    app.kubernetes.io/name: frigate
  name: frigate
  namespace: frigate
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: frigate
      app.kubernetes.io/name: frigate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: frigate
        app.kubernetes.io/name: frigate
    spec:
      containers:
        - image: ghcr.io/blakeblackshear/frigate:stable-h8l
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 10
          name: frigate
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
            - containerPort: 8971
              name: http-auth
              protocol: TCP
            - containerPort: 1935
              name: rtmp
              protocol: TCP
            - containerPort: 8554
              name: rtsp
              protocol: TCP
            - containerPort: 8555
              name: webrtc-udp
              protocol: UDP
            - containerPort: 8555
              name: webrtc-tcp
              protocol: TCP
            - containerPort: 1984
              name: go2rtc-admin
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 10
          resources: {}
          securityContext: {}
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
            - mountPath: /media
              name: media
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /tmp
              name: tmp
            - mountPath: /config/config.yaml
              name: vault-config
              subPath: config.yaml
            - mountPath: /dev/hailo0
              name: h8l
      nodeSelector:
        k8s.dalmura.cloud/nodegroup: eq14-worker-pool
      volumes:
        - name: config
          emptyDir: {}
        - name: data
          emptyDir: {}
        - name: media
          persistentVolumeClaim:
            claimName: frigate-media
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: vault-config
          secret:
            secretName: frigate-values
        - name: h8l
          hostPath:
            path: /dev/hailo0
