---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frigate-secrets
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: frigate-secrets
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: workload-reader-frigate-secrets
    serviceAccount: frigate-secrets
    audiences:
      - vault
