apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: frigate-secrets-config
spec:
  type: kv-v2

  mount: site
  path: wave-5/frigate/values

  destination:
    name: frigate-values
    create: true

  # static secret refresh interval
  refreshAfter: 5m

  vaultAuthRef: frigate-secrets
