apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://stakater.github.io/stakater-charts/
      chart: reloader
      targetRevision: 2.2.4
      helm:
        valueFiles:
        - $values/sites/indigo/clusters/dal-indigo-core-1/wave-0/values/reloader/values.yaml
    - repoURL: https://github.com/dalmura/infrastructure.git
      targetRevision: HEAD
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: reloader
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 2
