---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-route53-credentials-secret
  namespace: cert-manager
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAza8t5u5Oo8vK84hAIiyRETt0mlU90g/dhD/MM94DY1Wd5XfbPcGerKWir++nMHwQMySWU1pxC0MCHVJmsLyHwL4WoZq1O5p+FtIvujjauLw43LhXMCK1SaqzcDMr2j9W/0G2Lu28PY2PQJTuYAqY6VV87yiDSYX9n5FqoNmdsGzD33r8OCkUcO2UtTUBPOEjRonLcCJjR4nmzV04hOs7CKZC/98q901Hq2cKdVIrykY8HOp4Hik0f3xaKQ5SwKjl3pT1Eg8lAXJuK01SuRqy+xjGbm4k7lq1caKmaBCiyHsjL1ISbrh5WboMi+iKYW26hfJDp6DMVzsZ0iA2Qlce1f03jclKFgI+GHXBlALllyseyuNGtiA0/qpmknMFx+i8F6KF68L/PnCZpaBDBv94TlNyghkbKpnvUDPN3QO6QJNcj3UobT+RONSAZXPRHFcGtsBYN7cPlD9XKacpyTUUk617LyxW3nnxFrZvDE38ptO1M5Kt/jzZPl4fkny1yCmBV01fdw+pHkVa9ZZrjbBiDgMUpB/TezId57x/CtShxzu4VddlVVcK8xfJNMvLSQOQ4SxTiVYvGRvEbphCBTULpdlT690fXcmK6WAAIxI3zg5A/RBmwAChaJ5w51vvySorcHGQxGDKd8iBsv9S0o4ASjdAIKGg3S68ESKc6xnZ01KR1ua1RmE48e3kFywZF1Ap3T2yn7cO4IhoctaLCzA0POMRNew==
    SECRET_ACCESS_KEY: AgBhOkSypGlnFpjyOfYi9OLsD8gQlRNky7UXeiJpjSwP76/08pPDHhwmkgE+K5Zw3/FeyfNW1Qkl7aW1hqWsUwz/vM9Yim8ddRsCTiWgXgJQ3amh3ao6OyuO5RVLTgaKMFZ2rhOMYRev0bS/xsENFdrqoqbv32zvjRZ06r5iLCCkx+gYiVTi1c0OPW2oyzCpzZShdH+PCgNNXJjT/s+L+v9QYtd6iZHrneCll04kwHBZxRYhBkMaAvkdwzHeVkYm1RzZhLde30e4FvwEwbjaZeXBbkL8rfHnTI5Y9LDiZ7JfVfW/Wkt+jxJxvGQopoPtUznhR1cXlUCE59HN5F5A4Wps2Gu/r9nt5DHfXKsmrsFV3fubzR1Yjln7wkalWykpQFOK+WWTpPz13BBxHCaD3mfVzxx8+S6TwwB1IOhdWkbSFPa39Z9fCeshL81HrZztrtfvWUe6u3MJAU90+gwWhLvljfBl/qBnPwX6OmBbJQwS0ed+TALCg8H/FpqLE3M6o+/S+zD/kvl2eCf1AbJbEE9tyblmlk61/46Y6CrCAmO0ybIN7XxyCRHDqRqIx8+Sl+20Z2oP8mR9GG4ReBJQQQ3Lnk8RFnUQVd/m32qD2Kxy8B4OVMhfnmvFtOfBHeQLQocxZ75PpQBU78xSx5FXxIdJLESnMh5TqfxCMcxJ/KVNYR9ZQy9GzTZDh8Qcwd4vomMmPI/4Qy9p13pJGAbfzwKJULtHJ89RoYERyOqOJFmHHQdiQuIHDRKj
  template:
    metadata:
      creationTimestamp: null
      name: aws-route53-credentials-secret
      namespace: cert-manager
