apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: forgejo-secrets-config
spec:
  type: kv-v2

  mount: site
  path: wave-5/forgejo/env

  destination:
    name: forgejo-env
    create: true

  # static secret refresh interval
  refreshAfter: 5m

  vaultAuthRef: forgejo-secrets
