---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: forgejo-secrets
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: workload-reader-forgejo-secrets
    serviceAccount: forgejo
    audiences:
      - vault
