apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dalmura/workloads.git
    path: sealed-secrets
    targetRevision: HEAD
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
