apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-secrets
spec:
  secretStoreRef:
    name: site
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: 1h

  data:
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: wave-5/obsidian-livesync/couchdb-secrets
        property: ADMIN_USERNAME

    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: wave-5/obsidian-livesync/couchdb-secrets
        property: ADMIN_PASSWORD

    - secretKey: COOKIE_AUTH_SECRET_KEY
      remoteRef:
        key: wave-5/obsidian-livesync/couchdb-secrets
        property: COOKIE_AUTH_SECRET_KEY

    - secretKey: ERLANG_COOKIE_KEY
      remoteRef:
        key: wave-5/obsidian-livesync/couchdb-secrets
        property: ERLANG_COOKIE_KEY
