---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: obsidian-livesync
    app.kubernetes.io/name: obsidian-livesync
  name: obsidian-livesync
  annotations:
    cert-manager.io/cluster-issuer: dalmura-letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: obsidian-livesync.indigo.dalmura.cloud
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: true
spec:
  ingressClassName: ingress-private
  tls:
    - hosts:
        - obsidian-livesync.indigo.dalmura.cloud
      secretName: obsidian-livesync-cert
  rules:
  - host: obsidian-livesync.indigo.dalmura.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: obsidian-livesync-couchdb
            port:
              number: 5984
