---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dolores-assistant-secret
  namespace: dolores-assistant
spec:
  encryptedData:
    DOLORES_SERVICE_TOKEN: AgBbtSia5MNjKSXQyWr7EQk2TW04ES1BghZwH9veoU2IIxkRae1IR20b75wSsLzKgthwIDZ45lo5dtqfJd1q37vLmL7ckC13XcNdlabz2949Zf0RfNH/8l6808XbmJfyDDY8zCuXJvMfVhmfUaw5dEB3dBgfr6A4uuk793jI8nmx6aWuGejcBLbJYvnWreiNpPjOyTsC37vCvh6UsswjppVYNLGprL/sXbC3Q/PdSrqGvdq5x7WO5gBPaKucDbrfs8qa1RaZ4P6vy/5jrKto+FDvIteKdEsDTVeIcX41o+w9KdJDeMv3An2+rIcYyHB9UeWF7uE8M2sY7XIzk6zuu0feQiOvJwN63Cv40DEtepMRL2rtapUbZnzP4gR8ENmxI/GjZeeV+N/e2ZU2RuqlBKnFNP8XUTbTW8YHDCTQDFqzg1xtHzub7qj7eMMLHkFp5RBL9Ff077OmR4Cc3Xt/byxbuph4X1i1sn9/Y/4zT/T71JpM9kFMMDyIDIQhxmUtKbmmsuNHeiTD2EAhRDesAtUbrjmg/mTM4dmHxpLGr7AiDsKdQvAgsp5vkAkqWcUy5BYT7DLcZ3F4Sd4eDF5pHdnI4JY1vxiQKzA8+Dr8j6SW6mBYuL+5UKz9fjVtu3gB9pXDG17M2+Vl4nHFtmfOSghaDBysAlfWSyXgypkD9oOS8ttxwhz3JIamxjV0uCLqfGXjH6L2QQX0ubSuT/wfZy+kjgw0jX+t9WxTNtzVsHwzoaTRtaJHNGgzaYwr+n+yB0/upMZjpS6U2xnv2z0s/TJ+
  template:
    metadata:
      name: dolores-assistant-secret
      namespace: dolores-assistant
    type: Opaque
