apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anubis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dalmura/infrastructure.git
    path: sites/indigo/clusters/dal-indigo-core-1/wave-2/overlays/anubis
    targetRevision: HEAD
  destination:
    namespace: anubis
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 2
