apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      targetRevision: 0.20.2
      helm:
        valueFiles:
        - $values/sites/indigo/clusters/dal-indigo-core-1/wave-3/values/cloudnativepg/values.yaml
    - repoURL: https://github.com/dalmura/infrastructure.git
      targetRevision: HEAD
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cnpg-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 2
