apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/headlamp/
      chart: headlamp
      targetRevision: 0.39.0
      helm:
        valueFiles:
        - $values/sites/indigo/clusters/dal-indigo-core-1/wave-2/values/headlamp/values.yaml
    - repoURL: https://github.com/dalmura/infrastructure.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/dalmura/infrastructure.git
      path: sites/indigo/clusters/dal-indigo-core-1/wave-2/overlays/headlamp
      targetRevision: HEAD
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: headlamp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 1
