apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ng-public
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: ghcr.io/traefik/helm
      chart: traefik
      targetRevision: 37.2.1
      helm:
        valueFiles:
        - $values/sites/indigo/clusters/dal-indigo-core-1/wave-2/values/traefik-public/values.yaml
    - repoURL: https://github.com/dalmura/infrastructure.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/dalmura/infrastructure.git
      path: sites/indigo/clusters/dal-indigo-core-1/wave-2/overlays/traefik-public
      targetRevision: HEAD
  destination:
    namespace: traefik-public
    server: {{ .Values.spec.destination.server }}
  revisionHistoryLimit: 2
