---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: archestra-db
spec:
  description: "Archestra DB"
  instances: 1
  enablePDB: false

  enableSuperuserAccess: true

  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: archestra
      owner: archestra
      postInitApplicationSQL:
        - "CREATE EXTENSION IF NOT EXISTS vector;"

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 2Gi

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 18

  storage:
    storageClass: cluster-nobackup
    size: 20Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: archestra-postgres

  postgresql:
    parameters:
      archive_timeout: "30min"
      max_connections: "200"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: archestra-db-backup
spec:
  cluster:
    name: archestra-db
  schedule: "0 20 16 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
