---
nameOverride: vms

rbac:
  extraRules:
    # node-exporter read permissions
    - apiGroups: [""]
      resources: ["services/node-exporter-prometheus-node-exporter"]
      verbs: ["get"]

server:
  retentionPeriod: 6M

  extraArgs:
    vmalert.proxyURL: http://victoria-metrics-alert-vma-server.victoria-metrics.svc.cluster.local:8880/

  scrape:
    enabled: true

    extraScrapeConfigs:
      - job_name: victoria-logs-single
        static_configs:
          - targets:
              - http://victoria-logs-single-vls-server.victoria-logs.svc.cluster.local:9428/metrics
      # Longhorn metrics suck, the service only sends you to _one_ of the manager pods
      # And each manager pod serves up its own metrics
      # So there's no simple way to scrape all pods combined
      # See below for how to properly do it
      #- job_name: longhorn
      #  static_configs:
      #    - targets:
      #        - http://longhorn-backend.longhorn-system.svc.cluster.local:9500/metrics
      - job_name: longhorn
        scrape_interval: 1m0s
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            regex: "longhorn-system"
            action: keep
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: "longhorn-manager"
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: "9500"
            action: keep
      - job_name: node-exporter
        scheme: https
        # Use the default token that Kubernetes automatically mounts into the vmagent pod
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        tls_config:
          insecure_skip_verify: true
        scrape_interval: 30s
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: .*node-exporter.*
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: metrics|https
          - source_labels: [__meta_kubernetes_node_name]
            action: replace
            target_label: instance

    action: keep

  persistentVolume:
    size: 20Gi
    storageClassName: cluster-nobackup

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: dalmura-letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: vms.indigo.dalmura.cloud
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: authentik-authentik@kubernetescrd
    hosts:
      - name: vms.indigo.dalmura.cloud
        path:
          - /
        port: http
    ingressClassName: ingress-private
    tls:
      - hosts:
          - vms.indigo.dalmura.cloud
        secretName: vms-cert
