apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
        - name: external-dns
          args:
            - --events
            - --source=service
            - --source=ingress
            - --source=crd
            - --provider=aws
            - --registry=txt
            - --txt-owner-id=dal-indigo-core-1
            - --txt-prefix=dal-
            - --domain-filter=dalmura.cloud
            - --domain-filter=dalmura.au
          env:
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /.aws/credentials
          volumeMounts:
            - name: iam-credentials
              mountPath: /.aws
              readOnly: true
      volumes:
        - name: iam-credentials
          secret:
            secretName: iam-credentials
