cert-manager:
  installCRDs: false

external-dns:
  crd:
    create: false

integrations:
  certManager:
    enabled: true
    certificateTemplate: {}
    issuer: dalmura-letsencrypt-prod

  externalDNS:
    enabled: true

    targetService:
      namespace: traefik-private
      name: traefik-ingress-controller

selector:
  ingressClass: ingress-private
