apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - postgres.yaml
  - network-policy-evolution-api.yaml
  - network-policy-postgres.yaml
  - secret.sealed.yaml
