---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: whatsapp-secrets
  namespace: whatsapp
spec:
  encryptedData:
    api-key: AgDE9ibLhRELCI2353XCKwzFADULIHfIMfJjnP4v3ic1I/MdsUIQKwqACpqLc+b8PC8D4kOQJqcmjMD6vMxLF25PjZeIpkHXqj0Zd+e8W6/0aBtm2Yp+A9DdCcVXinhTGeEYi8u65Hk0h0SJbWGf/iq+C/BTgVNf8hXyJXOaKRicsyzhkbQPD6SJ3v8TZKClDkW4xiGSWob4GHR8SejdLva2p+29mY/TPF75FhoFBsaCmGN++xzYTXcF24fdrVzigQb4C7FuxHpAuTkFIftZikzG+TmR1/v32NZzaatpGoqUjEH1jMxozaV6TvqpwV2XQAnh2sZYQzYnQvZYrJsNPyONuO9I7vbErx87ffT/1Y55kCFYriol6egbya2+jdRpFKfugmWyXk6oMyprPbyZgupp8h3WcjSX+q3gKAdTBUPXPxakN1Yhxqd6ePfXviCQFHYscSIu2ul/8+fwWZsJHQGh5GtKCAyR0cYJM6M2HsUJRVrVyKsJ1hL8Lh6XiXc4ygWNzI3+2C7Ey5m7AoLS+8UFHqYCYuZdBeefNnl5zW/vOdcipK2REtr7k73US2SXJU8HNanTb9chHsWJ1iOk7ceGP7trtBoRxttPwg+FW73vvTRgF0oQ4Y5MXcSnfIh+clfmF3/iTVWPeOSVLcHWEoJgh510cviG/sPLY+GtZh5Z8UAjNEVYcQDE0r0f4a7YG0gV6yx+pf2UIJLfK0+Vpfz1pejOZ0ANsKe8t1W2QJI=
  template:
    metadata:
      name: whatsapp-secrets
      namespace: whatsapp
    type: Opaque
