apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Use of switchboard allows for automatic discovery for cert-manager and external-dns
  - ingressroute.yaml

  # Eventually need to move to Gateway API instead
