apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: indigo
spec:
  instances: 1
  ingress:
    enabled: false
  db:
    vendor: postgres
    host: keycloak-db-rw
    usernameSecret:
      name: keycloak-db-app
      key: username
    passwordSecret:
      name: keycloak-db-app
      key: password
    database: app
  http:
    tlsSecret: keycloak-cert
  hostname:
    hostname: https://auth.indigo.dalmura.cloud:443
    admin: https://admin.auth.indigo.dalmura.cloud:443
  proxy:
    headers: xforwarded
