apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: indigo
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-db-rw
    usernameSecret:
      name: keycloak-db-app
      key: username
    passwordSecret:
      name: keycloak-db-app
      key: password
  http:
    tlsSecret: keycloak-cert
  hostname:
    hostname: auth.indigo.dalmura.cloud
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
  log_level: DEBUG
