---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-db-backup-secret
  namespace: keycloak
spec:
  encryptedData:
    ACCESS_KEY_ID: AgDB5rYQqz2g8mMrODeJmrHuZUhwfAfo/AjD8RgAYR1CgiEPe//AGPV8/aIPEs/4Q32SrYn4UgFb4jcIB0/rbazyOnl24zX+juaNC7XLtvcAmU6zt53CkYu+lHw/VcKydMRyOSC34ONCEidUbh995cgl4gxLrxJg3GRYyLUDfpF5iCrUsVo/bXW1izFDdK7n7o4gY5a1oDr2DRG2hJDcrLoTLgLk6H+xI0nzHhY1oTm/5N4fBmGpKWE4JTPHE9Beh7HaT9pXWefFaFyw+7o2fyY/KT0wNHlJ/YBURKXsh/wsjX0JMyYk3Qquw3HF8a5KVuJbSKT81e1Kr8bQ6lqZD64AtY4Oy9lAhNtuwHIXxBie9qepiRaUF/TGsHSkKTDNzE/7wfmgXhjC4McPnAFtBXd5SrIyMsguy1B8XLUxX4MUwnx0alGKetwtDI6CsmNfFlCET13rIPoEbvNkihFZHWcQGkFQ2D+4FGDOyWq7IZ5F3LA2EbVHrWlRFtNVxwfHWMGJQl5hUKJiXIp1pC75BImT8LF0I3SgzNhDGvo+Ywie3yoSGUYWDxbnZgCRQDbiSPOfYO7KTF2QRKN8c2ChLNF2Ll/4sR40/Mj83lPsky9wcbBZBzRYD5w9pC7AE6XCCWkV6jkHpuTK9QXui5TJ+CKZVpH1fTHE5I2Uo56M5j+5PWRWZuLGZlLMnHxqssr7QfCwO01WcvoV1OqxS7THgUj+LpXjcQ==
    SECRET_ACCESS_KEY: AgAjiM0q/v1Lp4yk6IcSWtuoXM1ln//EIhrj8OYh/zCw9SunO7eDNWKc0JE9QiFcPq1QjSC+84kDtI1fHdhKQqgfZFAs0wEVXNJR78GMRechroxqRbF8m6APWzz4HzThFZbco5+Msr2bJtni4+aJOiWhrhBBncvtcAntrtin2JO1uxE6y0SE6NJn+VuezpkvsoDtviLg1jI4EKMm6FlyO2yVVbSMbYO6gaZfimOMSOCCWYcNXBEFG1ArGqlXo96azViliZsMVfAwESCbGfTn4fcYdUrxqwWHw/b2dmoCU5Xqnjye6y2HqFKDF0uVfZC70u29+Pc28i7+zV1dMkuKwryd63372LhRZHw8RvdgWzmdNBtUwUPwE/9DfLqW3jxPsutruhLu5NrcHJGh3EWgdZBl18lKLKGP9ytMfzqg8+wsNGKthXwRXCel8hK4z45FpiFtS+lngIz9bmBI2zwB20DzmxccvnkveM2DzdkylJpEef2VANw592dZQK2DgnzdiPKu1tlEJtHDDWzo+4fJjJ/SnubVJCNtBlBr4ofAWtvVGNXOtcA07A88SWZqP5sCjC3Js9OmeJEWNvsVFZDVWighLiGbDFQ6EMQWSgbs3bkuti2YQ3c13K3E5kEWOzFTMKxx+VzMqaHJk5o88ozrFz2/ybifObM5B6Mv9aGuLSFPzjiDnqPD3AyLGK7oDshX43t4HeVB854RiMAcbrMAJHxgxaOVGkf+TUIBEoD60vQvF4RHt2tzJg1G
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-db-backup-secret
      namespace: keycloak
