apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
spec:
  description: "Keycloak DB"
  instances: 1

  enableSuperuserAccess: true

  primaryUpdateStrategy: unsupervised

  storage:
    storageClass: longhorn-nobackup
    size: 10Gi
