apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.19.0
      helm:
        valueFiles:
        - $values/sites/indigo/clusters/dal-indigo-core-1/wave-3/values/external-secrets/values.yaml
    - repoURL: https://github.com/dalmura/infrastructure.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/dalmura/infrastructure.git
      path: sites/indigo/clusters/dal-indigo-core-1/wave-3/overlays/external-secrets
      targetRevision: HEAD
  destination:
    namespace: external-secrets
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 1
