apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dalmura/workloads.git
    path: keycloak-operator
    targetRevision: HEAD
  destination:
    namespace: keycloak
    server: {{ .Values.spec.destination.server }}
  revisionHistoryLimit: 2
