apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dolores-brain
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/dalmura/infrastructure.git
      path: sites/navy/clusters/dal-navy-core-1/wave-5/overlays/dolores-brain
      targetRevision: HEAD
  destination:
    namespace: dolores-brain
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 1
