apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "site"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "auth-role-operator"

          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
