apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/metallb/metallb
    path: config/native
    targetRevision: v0.13.9
  destination:
    namespace: metallb-system
    server: {{ .Values.spec.destination.server }}
