apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  endpointSelector:
    matchLabels:
      io.kubernetes.pod.namespace: home-assistant
  ingress:
    # Allow traffic from Traefik Private
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: traefik-private
            app.kubernetes.io/name: traefik
      toPorts:
        - ports:
            - port: "8123"
              protocol: TCP
            - port: "8080"
              protocol: TCP
  egress:
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    # Allow egress to Frigate API
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: frigate
            app.kubernetes.io/name: frigate
      toPorts:
        - ports:
            - port: "5000"
              protocol: TCP
