apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server-data
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: matter-server
    app.kubernetes.io/instance: matter-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cluster-regular
  resources:
    requests:
      storage: 2Gi
