kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
spec:
  template:
    spec:
      containers:
        - name: traefik
          args:
            - --global.checknewversion=false
            - --global.sendAnonymousUsage=false
            - --api.insecure=true
            - --api.dashboard=true
            - --entryPoints.web.address=:80
            - --entryPoints.websecure.address=:443
            - --providers.kubernetesingress
            - --providers.kubernetesingress.ingressClass=ingress-public
            - --providers.kubernetesingress.ingressEndpoint.publishedService=traefik-public/traefik-ingress-controller
            - --providers.kubernetescrd.ingressclass=ingress-public
            - --providers.kubernetescrd.allowCrossNamespace=true
            - --serversTransport.insecureSkipVerify=true
            - --experimental.plugins.geoblock.modulename=github.com/PascalMinder/geoblock
            - --experimental.plugins.geoblock.version=v0.3.3
            - --experimental.plugins.fail2ban.modulename=github.com/tomMoulard/fail2ban
            - --experimental.plugins.fail2ban.version=v0.8.7
            #- --log.level=DEBUG
            #- --accesslog=true
