container_runtime: containerd

agent:
  enabled: false

secrets:
  externalSecret:
    name: crowdsec-secrets
    csLapiSecretKey: csLapiSecret
    registrationTokenKey: registrationToken

appsec:
  enabled: true
  configs:
    crs-blocking.yaml: |
      name: custom/crs-blocking
      default_remediation: ban
      inband_rules:
        - crowdsecurity/crs
      pre_eval:
        - filter: IsInBand == true && req.Host == "auth.indigo.dalmura.cloud" && req.URL.Path startsWith "/api/v3/flows/executor/"
          apply:
            - SetRemediation("allow")
        - filter: IsInBand == true && req.Host == "auth.indigo.dalmura.cloud" && req.URL.Path startsWith "/if/flow/default-authentication-flow/"
          apply:
            - SetRemediation("allow")
        - filter: IsInBand == true && req.Host == "auth.indigo.dalmura.cloud" && req.URL.Path startsWith "/if/flow/default-provider-authorization-implicit-consent/"
          apply:
            - SetRemediation("allow")
        - filter: IsInBand == true && req.Host == "auth.indigo.dalmura.cloud" && req.URL.Path startsWith "/application/o/authorize/"
          apply:
            - SetRemediation("allow")
        - filter: IsInBand == true && req.Host == "anubis.indigo.dalmura.cloud" && req.URL.Path startsWith "/.within.website/"
          apply:
            - SetRemediation("allow")
  acquisitions:
    - source: appsec
      listen_addr: 0.0.0.0:7422
      path: /
      appsec_configs:
        - "crowdsecurity/appsec-default"
        - "custom/crs-blocking"
      labels:
        type: appsec
  env:
    - name: COLLECTIONS
      value: "crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules crowdsecurity/appsec-crs crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/base-http-scenarios"

lapi:
  env:
    - name: COLLECTIONS
      value: "crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules crowdsecurity/appsec-crs crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/base-http-scenarios"
    - name: BOUNCER_KEY_traefik_bouncer
      valueFrom:
        secretKeyRef:
          name: crowdsec-bouncer
          key: key
    - name: ENROLL_KEY
      valueFrom:
        secretKeyRef:
          name: crowdsec-enrollment
          key: ENROLL_KEY
    - name: ENROLL_INSTANCE_NAME
      valueFrom:
        secretKeyRef:
          name: crowdsec-enrollment
          key: ENROLL_INSTANCE_NAME
    - name: ENROLL_TAGS
      valueFrom:
        secretKeyRef:
          name: crowdsec-enrollment
          key: ENROLL_TAGS

  persistentVolume:
    data:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      storageClassName: cluster-regular

config:
  config.yaml.local: |
    api:
      server:
        auto_registration: # Activate if not using TLS for authentication
          enabled: true
          token: "${REGISTRATION_TOKEN}" # /!\ Do not modify this variable (auto-generated and handled by the chart)
          allowed_ranges: # /!\ Make sure to adapt to the pod IP ranges used by your cluster
            - "127.0.0.1/32"
            - "192.168.0.0/16"
            - "10.0.0.0/8"
            - "172.16.0.0/12"
    db_config:
      flush:
        bouncers_autodelete:
          cert: 1h
          api_key: 1h
        agents_autodelete:
          cert: 6h
          api_key: 6h
