container_runtime: containerd

agent:
  enabled: false

  # We run with AppSec enabled, so we don't need hostPath log collection
  #acquisition: []
  #volumes: []
  #volumeMounts: []
  #env:
  #  - name: LEVEL
  #    value: info

appsec:
  enabled: true
  env:
    - name: COLLECTIONS
      value: "crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules"
  acquisitions:
    - appsec_configs:
        - crowdsecurity/appsec-default
      labels:
        type: appsec
      listen_addr: 0.0.0.0:7422
      path: /
      source: appsec

lapi:
  env:
    - name: BOUNCER_KEY_traefik_bouncer
      valueFrom:
        secretKeyRef:
          name: crowdsec-bouncer
          key: key

  persistentVolume:
    data:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      storageClassName: cluster-regular

config:
  collections:
    - crowdsecurity/traefik
    - crowdsecurity/http-cve
    - crowdsecurity/whitelist-good-actors
    - crowdsecurity/base-http-scenarios
    - crowdsecurity/appsec-virtual-patching
    - crowdsecurity/appsec-generic-rules
