cert-manager:
  installCRDs: false

external-dns:
  crd:
    create: true

integrations:
  certManager:
    enabled: true
    certificateTemplate:
      spec:
        issuerRef:
          kind: ClusterIssuer
          name: dalmura-letsencrypt-prod
    issuer: dalmura-letsencrypt-prod

  externalDNS:
    enabled: true

    targetService:
      namespace: traefik-public
      name: traefik-public

selector:
  ingressClass: ingress-public
