
image:
  tag: stable-h8l

extraVolumeMounts:
  - name: h8l
    mountPath: /dev/hailo0

persistence:
  media:
    enabled: true
    size: 50Gi

nodeSelector:
  k8s.dalmura.cloud/nodegroup: eq14-worker-pool
