---
image:
  tag: stable-h8l

extraVolumes:
  - name: vault-config
    secret:
      secretName: frigate-values
  - name: h8l
    hostPath:
      path: /dev/hailo0

extraVolumeMounts:
  - name: vault-config
    mountPath: /config/
    subPath: config.yaml
  - name: h8l
    mountPath: /dev/hailo0

config: "---"

persistence:
  media:
    enabled: true
    size: 50Gi

nodeSelector:
  k8s.dalmura.cloud/nodegroup: eq14-worker-pool
