---
image:
  tag: 0.16.0

extraVolumes:
  - name: h8l
    hostPath:
      path: /dev/hailo0

extraVolumeMounts:
  - name: h8l
    mountPath: /dev/hailo0

config: "---"

persistence:
  config:
    enabled: true
    storageClass: cluster-regular

  media:
    enabled: true
    size: 50Gi
    storageClass: cluster-nobackup

securityContext:
  # For the hailo0 mount to work
  privileged: true

nodeSelector:
  k8s.dalmura.cloud/nodegroup: eq14-worker-pool

service:
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https

auth:
  reset_admin_password: true
