---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secret-key
  namespace: authentik
spec:
  encryptedData:
    SECRET_KEY: AgC3n+xVWLG8u0CCzuHlUY/gH4KdDSUzcEPqc3feiKGeCyuzyDLAM9DO1vnAOVmJoWWbXIaDb62U2FUGA6NzTDc9hb8gRUg52yT9cLqFPmOYR5E5tVJxyBOCp6jeHqpY29JDJPttbWUTOx8lNKzfd/5IKZSmOU11Mb8gXXhPwPyUfdrVlgQQC6DtBNj+jDNDKkyS/Tapzo7x0BbGc+8avksomcOliY8EbDUWluJosuA/bbUw8EhJls0gxCmtIflrz19DaTvUQeCjAG4bMW7S0C17Wznq4ZmpE8CYFK2lHCTtj6LSFXJkWrHbyCU74Ru0Gk6rpQxpeUIRIGZubSkZW871ny23Ajfu8sha+2RHsv9IcWH6HOlK1E1DJFeDFi6EgRgvGldLclLe1ryarvI8PPg651XjGx2uSPUsFo2+bTquF/q1g9y01upHbDAux6KlN5mwemIe98G1X/TJL481SKznL/xzUYBCvPT4OfoiZ1UFgCj8KmIE8OPyf1QuRSQ3fGna0CoOpdxB/HDJbiyz7wHMZYbZUaXO/P1ruxlo3hKyL/BdrfR6aZG3KLP9dazCYpPzryGlcJu3Ylaa8qLV6OyhEUR0DzrqEI1itXWt8o7xCqgS3n+bxNdKbyg2qKbSyGB+J/22P198WxD4k5vTlNhYC5IA7mRvd9MzUuHW1QSFpNx2jURSy/e9Q60yD2CG+Zd3kJh9ACuYHBMJFzApWbxySHo79rQo5coeddZdZrGWU0z7YKHupIBPYYrvJWI86knuShHIk61ndjodU1odJQ+EI9N6of4o+9Ltq4La405T6g==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secret-key
      namespace: authentik
