---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-db-backup-secret
  namespace: authentik
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCqCYp5pehd4P9TiUYABD0BTs7jPSDd+EXeosBC+NklsV+fopw+ahtQnk16JdeyzulqCxeboqyq1RHkIEyS6XfKlIPua47pU9sOyjM5WDQPNrCOQoZMP1Qf5Wd6nMsQfL9vNbGXLKgCFKy6b64EDB8qomDID49QFzzcUvVwv0u1ga/sdY/4zNzRpBDoHh77+oO3oGGHRxb99vRCQKirk6RJ4GBw+8y7HdOezOJ0XhoGS4h9nzGK3GaRjZRfG5XqDjz/YRLhkZFLEKlIRVzYqtSE1fsBzUKs89EzvRNneCY2waVwumzYL9Jn7kK5Sc/cd2wtzzt2OPn/yBVwRDK5AX1dabhX20UtUx2X0BlhlIlNJ3qLfYklN1sIo7hdsEO4CPYyhzzaeEMVROMU6sLbT7PwypiHEWefokdgp+NRobqtLFl2tLTJDyEeIxW8MOFTVT5GfKFEiMNaTDvHhso6qKGifUTDDslieTl6Oa4AefKiOqUFrc6UXAifrZrTOwdZ84rzxF484bbah+U8A2gf48r128y4WSRE0iW8TygYpbff0jNoJt9ABwGcBZGTeegOlxAbpCVqU2yekcbkZsQFePxJcY/FgboXXmmmpjHlPpSEuwTG9TDnwtUHZk+btp2DyuuDVUR9JE1+FZvs/QRNOt00vRBprNZXyfVLvwFq/lv+wgx9hwry3scsHW/7fQeV7vZsNScDnfFVwNFFqL9Q3AMOI1iDjg==
    SECRET_ACCESS_KEY: AgCWZPPM774CtdjcshonGVcMIWmLYbdKoGkVH2xL2depjmmkGoEv0hZSD0GNwQ2yQUNqN870wspX42EWORF49KzE2ttxjRgRULqxKjJ5ZTTS9sylFV8QMA8vkJE/Zz2VpFxqTgDsB6lPFCidRvTbjMdlaQuivRaLELcbHHL3VdJYSNXfI6D9nE36ljju8SfzHvM470pRGFErzB6qkXFhpJGTirNAiePYrSuiSbRI3kxeJW0I0IGhaFUZHPoDYyiCR8Tla6RHejeTtoPAvD9SLaaBpDtjUxvwiATpyAxpXab806isFlZehldMj5VUBRp+8qFZxIvzPZ7cHYN/wInhLWs4hAgMCz5Q772P3BlimgQogunPOUTpJDZCfkCH7pSMM1j4Mjq9GcuzAzzSPMyce7zc+uKYpipTp3fhFioFNuLOKf26afP9jvo2auMGKdY+eQFvAD7/GW3bZ4Cdt7Wk3U0pKfvyRAiMhbwdBtKho1ge2a6D/DBr+m02TIlVvvrXFjFpYwOA6YOsjlm5zFMS8yd+8PQRX5Ghmtkp5JBqWKopcgCjvGIe1S3YIVVl8Uz9r3AZGgv/jIpVDLTDm5UkEl4/8zM7T+Uqiua3JC9/rwXTvnfHXzPrgGGYchunr6DFV+XoUaeYNEHhZV/pMiCtl4dObsGlfbSCk+PWJLUI4Xe8CZ1J343bHiA49gTTeGAniewTGyIQlYH0s6wbta1uexRQ1tw6uvo14EZDob1MnjZjL1JcfYlWmE5F
  template:
    metadata:
      name: authentik-db-backup-secret
      namespace: authentik
