---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  encryptedData:
    SECRET_KEY: AgBt/7JhMbdAmIXOZY1V6cizZKKQHpKDWYuOL8ldraJhYiLHdOzaf2xMZrKcWADHblzZf/Pubzbe1bo2q+6/5V788nJKilJv8PuaYi+l+wQY8ueJNCrG0o95+guv6PG0pQDP1cQuJrBivEP4tYlP4wM/vi1WYOf9XQZLHbnQkqRi91Ssjyn84CZQPKm83gMLlCe55SZCqeMQSRnWdgIF3C+bD1xG7HrOtR3HjD9ucCzSFr4y3BVdkRM9vGOHBTvi+hEFbymk2yiNK4QccGNXYFvOzatXQ6Ka7c5hMk78+neXRgxfHgWP5ICWR/vgJT9gZ+b6QkSKEkmmBVz0Iz9XKcVIDD7YaHcPAH4sTSDr5n3WanKGVaYxdaXC35ZfAQN+pd6YJzOpRC0fpnrXI63XHBV90GPzAqaOIThBIWJfvrDvY92mSwU+frEATxz902BhYgGaNFoIxWZPFJdAgmBVTc826pSHqDT5ytng92H1xvv+xcejEl6QVacbzgjXZbRfzxnra8+UJMpg7sHqVgTXBNQ2F3CXjKQCk43Jbn8hx+xY0otTSV47ZTrYPfjw/f460qvnu8Ou8jxuETBcxPIOY65b3HQXs2opcCyg5dOCodsikjFa3gM9edF8RwNfC7uLtuvwRHz2BMG/wOAMPsvXfKrzMqj/n9NstHAHv0kTgH4itxOY0415yI0AQ4dcksr7G9DzGYAltiQTRZbgtPKbiB4pzEM89QZrslbSS97W2pX3BPdGi8LqvWt60D2CqgRUCDHfAxCHP9i37GYn/z24lvvWwhmZ5d7c28FpuPE9PftYlw==
  template:
    metadata:
      name: authentik-secret-key
      namespace: authentik
