apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authentik-csp
spec:
  headers:
    customResponseHeaders:
      Content-Security-Policy: "default-src 'self'; img-src https: data:; object-src 'none'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://challenges.cloudflare.com; frame-src https://challenges.cloudflare.com blob:; connect-src 'self' https://challenges.cloudflare.com;"
      Permissions-Policy: "camera=(), microphone=(), geolocation=(), usb=(), payment=(), screen-wake-lock=()"
      Cross-Origin-Opener-Policy: "same-origin-allow-popups"
      Cross-Origin-Resource-Policy: "same-origin"
