apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: authentik-redis
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: authentik
      app.kubernetes.io/component: master
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: authentik
  egress: []
