---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
spec:
  description: "Authentik DB"
  instances: 1

  enableSuperuserAccess: true

  primaryUpdateStrategy: unsupervised

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 18

  storage:
    storageClass: cluster-nobackup
    size: 20Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: authentik-postgres

  postgresql:
    parameters:
      archive_timeout: "30min"
      max_connections: "300"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-db-backup
spec:
  cluster:
    name: authentik-db
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
