apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://crowdsecurity.github.io/helm-charts
      chart: crowdsec
      targetRevision: 0.18.1
      helm:
        valueFiles:
        - $values/sites/indigo/clusters/dal-indigo-core-1/wave-6/values/crowdsec/values.yaml
    - repoURL: https://github.com/dalmura/infrastructure.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/dalmura/infrastructure.git
      path: sites/indigo/clusters/dal-indigo-core-1/wave-6/overlays/crowdsec
      targetRevision: HEAD
  destination:
    namespace: crowdsec
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 1
