---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: dal-k8s-core-1
  namespace: sidero-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.244.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: dal-k8s-core-1-cp
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalCluster
    name: dal-k8s-core-1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalCluster
metadata:
  name: dal-k8s-core-1
  namespace: sidero-system
spec:
  controlPlaneEndpoint:
    host: 192.168.77.3
    port: 6443
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalMachineTemplate
metadata:
  name: dal-k8s-core-1-cp
  namespace: sidero-system
spec:
  template:
    spec:
      serverClassRef:
        apiVersion: metal.sidero.dev/v1alpha1
        kind: ServerClass
        name: rpi4.4gb.arm64
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: dal-k8s-core-1-cp
  namespace: sidero-system
spec:
  controlPlaneConfig:
    controlplane:
      configPatches:
        - op: add
          path: /machine/network
          value:
            interfaces:
            - interface: eth0
              vlans:
                - dhcp: true
                  dhcpOptions:
                    routeMetric: 2048
                  vlanId: 103
                  vip:
                    ip: 192.168.77.3
              dhcp: true
              dhcpOptions:
                routeMetric: 1024
              vip:
                ip: 192.168.77.131
            nameservers:
              - 192.168.77.129
              - 192.168.77.1
      generateType: controlplane
      talosVersion: v1.3.1
    init:
      configPatches:
        - op: add
          path: /machine/network
          value:
            interfaces:
            - interface: eth0
              vlans:
                - dhcp: true
                  dhcpOptions:
                    routeMetric: 2048
                  vlanId: 103
                  vip:
                    ip: 192.168.77.3
              dhcp: true
              dhcpOptions:
                routeMetric: 1024
              vip:
                ip: 192.168.77.131
            nameservers:
              - 192.168.77.129
              - 192.168.77.1
      generateType: init
      talosVersion: v1.3.1
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalMachineTemplate
    name: dal-k8s-core-1-cp
  replicas: 1
  version: v1.26.0
