apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: photoprism-credentials
spec:
  secretStoreRef:
    name: site
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: 1h

  data:
  - secretKey: PHOTOPRISM_ADMIN_PASSWORD
    remoteRef:
      key: wave-5/photoprism/config
      property: admin_password
  - secretKey: PHOTOPRISM_OIDC_URI
    remoteRef:
      key: wave-5/photoprism/config
      property: oidc_uri
  - secretKey: PHOTOPRISM_OIDC_CLIENT
    remoteRef:
      key: wave-5/photoprism/config
      property: oidc_client
  - secretKey: PHOTOPRISM_OIDC_SECRET
    remoteRef:
      key: wave-5/photoprism/config
      property: oidc_secret
  - secretKey: PHOTOPRISM_OIDC_SCOPES
    remoteRef:
      key: wave-5/photoprism/config
      property: oidc_scopes
  - secretKey: PHOTOPRISM_OIDC_PROVIDER
    remoteRef:
      key: wave-5/photoprism/config
      property: oidc_provider
  - secretKey: PHOTOPRISM_OIDC_REDIRECT
    remoteRef:
      key: wave-5/photoprism/config
      property: oidc_redirect
  - secretKey: PHOTOPRISM_OIDC_REGISTER
    remoteRef:
      key: wave-5/photoprism/config
      property: oidc_register
