apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: photoprism
  namespace: photoprism
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: photoprism
      app.kubernetes.io/instance: photoprism
  ingress:
    # Allow traffic from Traefik Private
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: traefik-private
            app.kubernetes.io/name: traefik
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP

  egress:
    # Allow DNS
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
