apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reactive-resume-credentials
spec:
  secretStoreRef:
    name: site
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: 1h

  target:
    name: reactive-resume-secrets
    template:
      engineVersion: v2
      data:
        AUTH_SECRET: "{{ .auth_secret }}"
        OAUTH_CLIENT_ID: "{{ .oidc_client_id }}"
        OAUTH_CLIENT_SECRET: "{{ .oidc_client_secret }}"

  data:
  - secretKey: auth_secret
    remoteRef:
      key: wave-5/reactive-resume/config
      property: auth_secret
  - secretKey: oidc_client_id
    remoteRef:
      key: wave-5/reactive-resume/config
      property: oidc_client_id
  - secretKey: oidc_client_secret
    remoteRef:
      key: wave-5/reactive-resume/config
      property: oidc_client_secret
