apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: operator-oauth
spec:
  secretStoreRef:
    kind: SecretStore
    name: site

  refreshPolicy: Periodic
  refreshInterval: 1h

  data:
    - secretKey: client_id
      remoteRef:
        key: wave-6/tailscale/operator
        property: client_id

    - secretKey: client_secret
      remoteRef:
        key: wave-6/tailscale/operator
        property: client_secret
