apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-webfinger
spec:
  secretStoreRef:
    kind: SecretStore
    name: site
  refreshPolicy: Periodic
  refreshInterval: 1h
  data:
    - secretKey: webfinger
      remoteRef:
        key: wave-6/tailscale/webfinger
        property: content
