apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

# Force specific resources into different namespaces
namespaceConfiguration:
  - namespace: authentik
    resources:
      - name: authentik-well-known-tailscale
        kind: Ingress

resources:
  - secret-store-site.yaml
  #- external-secret.yaml
  # Webfinger setup required for tailscale tailnet setup
  - external-secret-webfinger.yaml
  - deployment-webfinger.yaml
  - service-webfinger.yaml
  - ingress-webfinger.yaml
  - network-policy-webfinger.yaml
  - ingress-authentik-tailscale.yaml

