apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale

resources:
  - secret-store-site.yaml
  - external-secret.yaml
  - proxygroup.yaml
  - proxyclass.yaml
  - service-relay.yaml

  # Webfinger setup required for tailscale tailnet setup
  # Commented out when not required
  #- external-secret-webfinger.yaml
  #- deployment-webfinger.yaml
  #- service-webfinger.yaml
  #- ingress-webfinger.yaml
  #- network-policy-webfinger.yaml

