---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: emojirades-db
spec:
  description: "Emojirades DB"
  instances: 1

  enableSuperuserAccess: true

  primaryUpdateStrategy: unsupervised

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 18

  storage:
    storageClass: cluster-nobackup
    size: 10Gi

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: emojirades-postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: emojirades-db-backup
spec:
  cluster:
    name: emojirades-db
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
