---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-db-backup-secret
  namespace: authentik
spec:
  encryptedData:
    ACCESS_KEY_ID: AgDKvwoD4yO8sO1qbeO3L5CQ86j3lp9IHUmo0Ml8AhaHVnH358zqGmbFljGhIH+hdLoIng8fxMKknFr6ecfWmJhcGyi4Czyd+kuhuLBdTRYUGu2gxgUoiYN8sojbam2Xj4pfgE/HgoMXdGzwqZbBzSifwmhZyUv9W5ar6uwobt9ky7Gs9DN9UhLFV0OQbk7drYNm7uPeQEQ+6JZNYKDIWQXD7HksxXRFuwMGLNztn6LQXlNTHjsKynebAbXcLNGWxmidXJtJSdrTiBCm8I5t8HtyCi897o262g7FcrAMbSvWk534fXrcYg4Df6zqy3neexOaggSzQba+i2tLdGe3tyQMULZ36K8vNHJ8fSr188pMBls/tWtWMmUQnmyX+vOooNmoq7PfXNMWK/PSvdSb+xLkULzH+mrFb4+DfwxSzQBEZZILE4wwCBVN2h0wsKXJ+40aj3tI6TIG00H3+TVsR8qz8kZnqmzhj+WA4qvZrIqT3DAhx6zuR3urhoKgal1cmbcnyJkvYnw1EfX23TOUqO9tk8KT+/2fJoNRu7Axy71nvAE04p5AzuhzrmMJPCrFq/0QINOAIxiUkPQKYUebnKgf9ldlpvwNf4wHWJoJKAMzoI598tv4HTIztVKjc5i7sLf4pZcr4y3QOlCFI60mj5yUAwTlTTyg9PRodKUva/AvhYlzuMvaL5qI6jeW9CNGDiwgoJ1Y4FHTdOA4egWv0ABU13C8LQ==
    SECRET_ACCESS_KEY: AgB98BLGRDzdGoqWV+q5yuEWAKBsgbMXSRz6MbqHnDBWpyPXbzJI6879BQHxDvlFgF8cNs6On31+/CSCUbMOWHzo7kyxtwJENCvcmMGQBExGAto6EE0iqSqCYOlUGHt1pC9FiITBe5p5SOxo2ZnJq8z8Yy6h6/kEoKkncSxMac6hWBqWEHeZVxaxGz+XKBeoD2gGaMlIk2VD9Ml1tk8tTVlr1HtNWUaUIRGTOUTYLUfCYfhHqdl+TKUNdCoX+OspRIw1JYjcJ6FVPCHwiIuw0brpvIB68A7+3+iC6QYzzCnHjMbS4KJaYG3oIDR6t7I+kSFdIoRXQ35sD4EWK/loXg4cizzU9x/xy9c9iIdXhx+MA7/wG3UWyz112VX4FjsfQrKMxiBgF7gjYYQRpRgTyPs5rKM+gYSIynUW2aiJqJ76P7GUIWf4SP0QZPqSigBJ3/1PyTl7QyPTuWb7qxzNcqTs+rc+CJ1rpvPkdqNGWWjmVpjIUH/GrpiDfJzdtbb4kdxwTLaQxRPx+TQuIHb7qptmY08GgHjUhlCwdxQI+weyOWXrTAyskBAOl2/jHRjJkR4Tvp/yPacdgaU0wNAwxlne547V4unyJ0GoWKiY45MN4lQjj1YqnFWArBO7YWX0dnS7oGa8srawYPqj4/Oi0HHS1dA/SUUftVZ0o+GSNNtmJCutRlyNMR9yw/fxJE9BwGZyGjXhMll0KrICq6KxvrR67AoqpWrb6b5l9sD4YXQt1uc9oH/F3J96
  template:
    metadata:
      creationTimestamp: null
      name: authentik-db-backup-secret
      namespace: authentik
