apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcaptcha
  namespace: authentik
  labels:
    app: mcaptcha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcaptcha
  template:
    metadata:
      labels:
        app: mcaptcha
    spec:
      containers:
        - name: mcaptcha
          image: mcaptcha/mcaptcha:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: http
          env:
            - name: MCAPTCHA_CONFIG
              value: "/etc/mcaptcha/config.toml"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mcaptcha-db-app
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mcaptcha-db-app
                  key: password
            - name: DATABASE_URL
              value: "postgres://$(DB_USER):$(DB_PASSWORD)@mcaptcha-db-rw:5432/app"
            - name: MCAPTCHA_server_cookie_secret
              valueFrom:
                secretKeyRef:
                  name: mcaptcha-secrets
                  key: cookie-secret
            - name: MCAPTCHA_SERVER_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: mcaptcha-secrets
                  key: cookie-secret
            - name: MCAPTCHA_captcha_salt
              valueFrom:
                secretKeyRef:
                  name: mcaptcha-secrets
                  key: salt
            - name: MCAPTCHA_CAPTCHA_SALT
              valueFrom:
                secretKeyRef:
                  name: mcaptcha-secrets
                  key: salt
          volumeMounts:
            - name: config-volume
              mountPath: /etc/mcaptcha
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: mcaptcha-config
---
apiVersion: v1
kind: Service
metadata:
  name: mcaptcha
  namespace: authentik
spec:
  ports:
    - port: 7000
      targetPort: 7000
      name: http
  selector:
    app: mcaptcha
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcaptcha-config
  namespace: authentik
data:
  config.toml: |
    debug = false
    source_code = "https://github.com/mCaptcha/mCaptcha"
    commercial = false
    allow_demo = false
    allow_registration = true

    [server]
    cookie_secret = "placeholder-replaced-by-env"
    port = 7000
    ip = "0.0.0.0"
    domain = "auth.navy.dalmura.cloud"
    proxy_has_tls = true

    [captcha]
    salt = "placeholder-replaced-by-env"
    gc = 30
    runners = 4
    queue_length = 2000
    enable_stats = true

    [captcha.default_difficulty_strategy]
    avg_traffic_difficulty =  50000
    avg_traffic_time =  1
    peak_sustainable_traffic_difficulty = 3000000
    peak_sustainable_traffic_time = 3
    broke_my_site_traffic_difficulty = 5000000
    broke_my_site_traffic_time = 5
    duration = 30

    [database]
    url = "postgres://placeholder-replaced-by-env"
    pool = 4

    [smtp]
    from = "admin@localhost"
    reply = "admin@localhost"
    url = "127.0.0.1"
    port = 10025
    username = "admin"
    password = "password"
