apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcaptcha
  namespace: authentik
  annotations:
    cert-manager.io/cluster-issuer: dalmura-letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: auth.navy.dalmura.cloud
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: traefik-public-geoblock@kubernetescrd
spec:
  ingressClassName: ingress-public
  tls:
    - hosts:
      - auth.navy.dalmura.cloud
      secretName: authentik-cert
  rules:
  - host: auth.navy.dalmura.cloud
    http:
      paths:
      - path: /captcha
        pathType: Prefix
        backend:
          service:
            name: mcaptcha
            port:
              number: 7000
