apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dalmura/infrastructure.git
    path: sites/navy/clusters/dal-navy-core-1/wave-2/overlays/argocd-ui
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
