apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg-image-catalog
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/dalmura/infrastructure.git
      path: sites/indigo/clusters/dal-indigo-core-1/wave-2/overlays/cloudnativepg-image-catalog
      targetRevision: HEAD
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
  revisionHistoryLimit: 2
