apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alert-manager-slack-config
spec:
  secretStoreRef:
    name: site
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: 1h

  data:
  - secretKey: webhook.yaml
    remoteRef:
      key: wave-4/victoria-metrics-alert/slack-config
      property: webhook.yaml
