apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - github.com/dalmura/workloads/keycloak-demo?ref=HEAD
  - ingress.yaml

patches:
  - path: deployment_override.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: keycloak
