---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: servers-vlan
  namespace: metallb-system
spec:
  ipAddressPools:
    - servers-vlan
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: servers-staging-vlan
  namespace: metallb-system
spec:
  ipAddressPools:
    - servers-staging-vlan
