apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-config
spec:
  secretStoreRef:
    name: site
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: 1h

  data:
  - secretKey: config.js
    remoteRef:
      key: wave-4/renovate/config
      property: config.js
