apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-config
spec:
  secretStoreRef:
    name: vault-site
    kind: ClusterSecretStore

  refreshPolicy: Periodic
  refreshInterval: 1h

  target:
    deletionPolicy: Delete

  data:
  - secretKey: config.js
    remoteRef:
      key: wave-4/renovate/config
      property: config.js
