---
persistence:
  defaultClass: false

preUpgradeChecker:
  jobEnabled: false
  upgradeVersionCheck: false

defaultSettings:
  allowCollectingLonghornUsageMetrics: false
  backupExecutionTimeout: 5

defaultBackupStore:
  backupTarget: "s3://dal-site-backups@us-east-1/indigo/"
  backupTargetCredentialSecret: aws-s3-credentials-secret
