apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stignore-manager-config
spec:
  secretStoreRef:
    name: site
    kind: SecretStore

  refreshPolicy: Periodic
  refreshInterval: 1h

  data:
    - secretKey: config.toml
      remoteRef:
        key: wave-5/stignore-manager/config
        property: config.toml
